package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBAggregates {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.aggregate_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String aggregate_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.virtual_type
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String virtual_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.storage_type
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String storage_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.zone
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.is_ha
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String is_ha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer job_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregates.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.id
     *
     * @return the value of aggregates.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.id
     *
     * @param id the value for aggregates.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.created_at
     *
     * @return the value of aggregates.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.created_at
     *
     * @param created_at the value for aggregates.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.updated_at
     *
     * @return the value of aggregates.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.updated_at
     *
     * @param updated_at the value for aggregates.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.aggregate_uuid
     *
     * @return the value of aggregates.aggregate_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getAggregate_uuid() {
        return aggregate_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.aggregate_uuid
     *
     * @param aggregate_uuid the value for aggregates.aggregate_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setAggregate_uuid(String aggregate_uuid) {
        this.aggregate_uuid = aggregate_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.name
     *
     * @return the value of aggregates.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.name
     *
     * @param name the value for aggregates.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.virtual_type
     *
     * @return the value of aggregates.virtual_type
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getVirtual_type() {
        return virtual_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.virtual_type
     *
     * @param virtual_type the value for aggregates.virtual_type
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setVirtual_type(String virtual_type) {
        this.virtual_type = virtual_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.storage_type
     *
     * @return the value of aggregates.storage_type
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getStorage_type() {
        return storage_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.storage_type
     *
     * @param storage_type the value for aggregates.storage_type
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setStorage_type(String storage_type) {
        this.storage_type = storage_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.zone
     *
     * @return the value of aggregates.zone
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.zone
     *
     * @param zone the value for aggregates.zone
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setZone(String zone) {
        this.zone = zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.is_ha
     *
     * @return the value of aggregates.is_ha
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getIs_ha() {
        return is_ha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.is_ha
     *
     * @param is_ha the value for aggregates.is_ha
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setIs_ha(String is_ha) {
        this.is_ha = is_ha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.owner_id
     *
     * @return the value of aggregates.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.owner_id
     *
     * @param owner_id the value for aggregates.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.creator_id
     *
     * @return the value of aggregates.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.creator_id
     *
     * @param creator_id the value for aggregates.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.job_id
     *
     * @return the value of aggregates.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.job_id
     *
     * @param job_id the value for aggregates.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregates.description
     *
     * @return the value of aggregates.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregates.description
     *
     * @param description the value for aggregates.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}