package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBAlerts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.prioritykey
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String prioritykey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.key2
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String key2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.value
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.time
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.id2
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String id2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.type2
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String type2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.priorityname
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String priorityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.unit
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.polices_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String polices_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.readed
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String readed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alerts.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.id
     *
     * @return the value of alerts.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.id
     *
     * @param id the value for alerts.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.created_at
     *
     * @return the value of alerts.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.created_at
     *
     * @param created_at the value for alerts.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.updated_at
     *
     * @return the value of alerts.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.updated_at
     *
     * @param updated_at the value for alerts.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.name
     *
     * @return the value of alerts.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.name
     *
     * @param name the value for alerts.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.prioritykey
     *
     * @return the value of alerts.prioritykey
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getPrioritykey() {
        return prioritykey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.prioritykey
     *
     * @param prioritykey the value for alerts.prioritykey
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setPrioritykey(String prioritykey) {
        this.prioritykey = prioritykey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.ip
     *
     * @return the value of alerts.ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.ip
     *
     * @param ip the value for alerts.ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.key2
     *
     * @return the value of alerts.key2
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getKey2() {
        return key2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.key2
     *
     * @param key2 the value for alerts.key2
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setKey2(String key2) {
        this.key2 = key2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.value
     *
     * @return the value of alerts.value
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.value
     *
     * @param value the value for alerts.value
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.description
     *
     * @return the value of alerts.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.description
     *
     * @param description the value for alerts.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.time
     *
     * @return the value of alerts.time
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.time
     *
     * @param time the value for alerts.time
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.id2
     *
     * @return the value of alerts.id2
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getId2() {
        return id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.id2
     *
     * @param id2 the value for alerts.id2
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId2(String id2) {
        this.id2 = id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.type2
     *
     * @return the value of alerts.type2
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getType2() {
        return type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.type2
     *
     * @param type2 the value for alerts.type2
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setType2(String type2) {
        this.type2 = type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.priorityname
     *
     * @return the value of alerts.priorityname
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getPriorityname() {
        return priorityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.priorityname
     *
     * @param priorityname the value for alerts.priorityname
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setPriorityname(String priorityname) {
        this.priorityname = priorityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.unit
     *
     * @return the value of alerts.unit
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.unit
     *
     * @param unit the value for alerts.unit
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.polices_id
     *
     * @return the value of alerts.polices_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getPolices_id() {
        return polices_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.polices_id
     *
     * @param polices_id the value for alerts.polices_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setPolices_id(String polices_id) {
        this.polices_id = polices_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.readed
     *
     * @return the value of alerts.readed
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getReaded() {
        return readed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.readed
     *
     * @param readed the value for alerts.readed
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setReaded(String readed) {
        this.readed = readed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.owner_id
     *
     * @return the value of alerts.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.owner_id
     *
     * @param owner_id the value for alerts.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alerts.creator_id
     *
     * @return the value of alerts.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alerts.creator_id
     *
     * @param creator_id the value for alerts.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }
}