package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBAlarmRules {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.meter_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String meter_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.alarm_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer alarm_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.comparison_operator
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String comparison_operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.threshold
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer threshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.alarm_actions
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Boolean alarm_actions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.ok_actions
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Boolean ok_actions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.insufficient_data_actions
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Boolean insufficient_data_actions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.evaluation_periods
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer evaluation_periods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.period
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.query
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String query;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.exclude_outlier
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Boolean exclude_outlier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.statistic
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String statistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.start
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_rules.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer job_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.id
     *
     * @return the value of alarm_rules.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.id
     *
     * @param id the value for alarm_rules.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.created_at
     *
     * @return the value of alarm_rules.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.created_at
     *
     * @param created_at the value for alarm_rules.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.updated_at
     *
     * @return the value of alarm_rules.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.updated_at
     *
     * @param updated_at the value for alarm_rules.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.meter_name
     *
     * @return the value of alarm_rules.meter_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getMeter_name() {
        return meter_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.meter_name
     *
     * @param meter_name the value for alarm_rules.meter_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setMeter_name(String meter_name) {
        this.meter_name = meter_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.alarm_id
     *
     * @return the value of alarm_rules.alarm_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getAlarm_id() {
        return alarm_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.alarm_id
     *
     * @param alarm_id the value for alarm_rules.alarm_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setAlarm_id(Integer alarm_id) {
        this.alarm_id = alarm_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.comparison_operator
     *
     * @return the value of alarm_rules.comparison_operator
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getComparison_operator() {
        return comparison_operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.comparison_operator
     *
     * @param comparison_operator the value for alarm_rules.comparison_operator
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setComparison_operator(String comparison_operator) {
        this.comparison_operator = comparison_operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.threshold
     *
     * @return the value of alarm_rules.threshold
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getThreshold() {
        return threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.threshold
     *
     * @param threshold the value for alarm_rules.threshold
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setThreshold(Integer threshold) {
        this.threshold = threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.alarm_actions
     *
     * @return the value of alarm_rules.alarm_actions
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Boolean getAlarm_actions() {
        return alarm_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.alarm_actions
     *
     * @param alarm_actions the value for alarm_rules.alarm_actions
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setAlarm_actions(Boolean alarm_actions) {
        this.alarm_actions = alarm_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.ok_actions
     *
     * @return the value of alarm_rules.ok_actions
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Boolean getOk_actions() {
        return ok_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.ok_actions
     *
     * @param ok_actions the value for alarm_rules.ok_actions
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOk_actions(Boolean ok_actions) {
        this.ok_actions = ok_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.insufficient_data_actions
     *
     * @return the value of alarm_rules.insufficient_data_actions
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Boolean getInsufficient_data_actions() {
        return insufficient_data_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.insufficient_data_actions
     *
     * @param insufficient_data_actions the value for alarm_rules.insufficient_data_actions
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setInsufficient_data_actions(Boolean insufficient_data_actions) {
        this.insufficient_data_actions = insufficient_data_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.evaluation_periods
     *
     * @return the value of alarm_rules.evaluation_periods
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getEvaluation_periods() {
        return evaluation_periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.evaluation_periods
     *
     * @param evaluation_periods the value for alarm_rules.evaluation_periods
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setEvaluation_periods(Integer evaluation_periods) {
        this.evaluation_periods = evaluation_periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.period
     *
     * @return the value of alarm_rules.period
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.period
     *
     * @param period the value for alarm_rules.period
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.query
     *
     * @return the value of alarm_rules.query
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getQuery() {
        return query;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.query
     *
     * @param query the value for alarm_rules.query
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setQuery(String query) {
        this.query = query;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.exclude_outlier
     *
     * @return the value of alarm_rules.exclude_outlier
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Boolean getExclude_outlier() {
        return exclude_outlier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.exclude_outlier
     *
     * @param exclude_outlier the value for alarm_rules.exclude_outlier
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setExclude_outlier(Boolean exclude_outlier) {
        this.exclude_outlier = exclude_outlier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.statistic
     *
     * @return the value of alarm_rules.statistic
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getStatistic() {
        return statistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.statistic
     *
     * @param statistic the value for alarm_rules.statistic
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setStatistic(String statistic) {
        this.statistic = statistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.start
     *
     * @return the value of alarm_rules.start
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.start
     *
     * @param start the value for alarm_rules.start
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setStart(String start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.owner_id
     *
     * @return the value of alarm_rules.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.owner_id
     *
     * @param owner_id the value for alarm_rules.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.creator_id
     *
     * @return the value of alarm_rules.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.creator_id
     *
     * @param creator_id the value for alarm_rules.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_rules.job_id
     *
     * @return the value of alarm_rules.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_rules.job_id
     *
     * @param job_id the value for alarm_rules.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }
}