package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBAlarmBindings {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_bindings.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_bindings.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_bindings.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_bindings.alarm_tmpl_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer alarm_tmpl_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_bindings.rule_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer rule_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_bindings.alarm_cml_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String alarm_cml_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_bindings.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String instance_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_bindings.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_bindings.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_bindings.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer job_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_bindings.id
     *
     * @return the value of alarm_bindings.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_bindings.id
     *
     * @param id the value for alarm_bindings.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_bindings.created_at
     *
     * @return the value of alarm_bindings.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_bindings.created_at
     *
     * @param created_at the value for alarm_bindings.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_bindings.updated_at
     *
     * @return the value of alarm_bindings.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_bindings.updated_at
     *
     * @param updated_at the value for alarm_bindings.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_bindings.alarm_tmpl_id
     *
     * @return the value of alarm_bindings.alarm_tmpl_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getAlarm_tmpl_id() {
        return alarm_tmpl_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_bindings.alarm_tmpl_id
     *
     * @param alarm_tmpl_id the value for alarm_bindings.alarm_tmpl_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setAlarm_tmpl_id(Integer alarm_tmpl_id) {
        this.alarm_tmpl_id = alarm_tmpl_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_bindings.rule_id
     *
     * @return the value of alarm_bindings.rule_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getRule_id() {
        return rule_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_bindings.rule_id
     *
     * @param rule_id the value for alarm_bindings.rule_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setRule_id(Integer rule_id) {
        this.rule_id = rule_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_bindings.alarm_cml_id
     *
     * @return the value of alarm_bindings.alarm_cml_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getAlarm_cml_id() {
        return alarm_cml_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_bindings.alarm_cml_id
     *
     * @param alarm_cml_id the value for alarm_bindings.alarm_cml_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setAlarm_cml_id(String alarm_cml_id) {
        this.alarm_cml_id = alarm_cml_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_bindings.instance_id
     *
     * @return the value of alarm_bindings.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getInstance_id() {
        return instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_bindings.instance_id
     *
     * @param instance_id the value for alarm_bindings.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setInstance_id(String instance_id) {
        this.instance_id = instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_bindings.owner_id
     *
     * @return the value of alarm_bindings.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_bindings.owner_id
     *
     * @param owner_id the value for alarm_bindings.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_bindings.creator_id
     *
     * @return the value of alarm_bindings.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_bindings.creator_id
     *
     * @param creator_id the value for alarm_bindings.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_bindings.job_id
     *
     * @return the value of alarm_bindings.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_bindings.job_id
     *
     * @param job_id the value for alarm_bindings.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }
}