package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBFlavors {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.vcpus
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer vcpus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.memory_mb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer memory_mb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.root_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer root_gb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.ephemeral_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer ephemeral_gb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.swap
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer swap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.is_public
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Boolean is_public;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavors.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.id
     *
     * @return the value of flavors.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.id
     *
     * @param id the value for flavors.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.created_at
     *
     * @return the value of flavors.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.created_at
     *
     * @param created_at the value for flavors.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.updated_at
     *
     * @return the value of flavors.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.updated_at
     *
     * @param updated_at the value for flavors.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.name
     *
     * @return the value of flavors.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.name
     *
     * @param name the value for flavors.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.vcpus
     *
     * @return the value of flavors.vcpus
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getVcpus() {
        return vcpus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.vcpus
     *
     * @param vcpus the value for flavors.vcpus
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setVcpus(Integer vcpus) {
        this.vcpus = vcpus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.memory_mb
     *
     * @return the value of flavors.memory_mb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getMemory_mb() {
        return memory_mb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.memory_mb
     *
     * @param memory_mb the value for flavors.memory_mb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setMemory_mb(Integer memory_mb) {
        this.memory_mb = memory_mb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.root_gb
     *
     * @return the value of flavors.root_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getRoot_gb() {
        return root_gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.root_gb
     *
     * @param root_gb the value for flavors.root_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setRoot_gb(Integer root_gb) {
        this.root_gb = root_gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.ephemeral_gb
     *
     * @return the value of flavors.ephemeral_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getEphemeral_gb() {
        return ephemeral_gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.ephemeral_gb
     *
     * @param ephemeral_gb the value for flavors.ephemeral_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setEphemeral_gb(Integer ephemeral_gb) {
        this.ephemeral_gb = ephemeral_gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.swap
     *
     * @return the value of flavors.swap
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getSwap() {
        return swap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.swap
     *
     * @param swap the value for flavors.swap
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setSwap(Integer swap) {
        this.swap = swap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.is_public
     *
     * @return the value of flavors.is_public
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Boolean getIs_public() {
        return is_public;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.is_public
     *
     * @param is_public the value for flavors.is_public
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setIs_public(Boolean is_public) {
        this.is_public = is_public;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.owner_id
     *
     * @return the value of flavors.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.owner_id
     *
     * @param owner_id the value for flavors.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavors.creator_id
     *
     * @return the value of flavors.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavors.creator_id
     *
     * @param creator_id the value for flavors.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }
}