package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBImages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.image_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String image_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.disk_format
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String disk_format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.container_format
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String container_format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.size
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.is_public
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Boolean is_public;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.min_disk
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer min_disk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.min_ram
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer min_ram;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.base_image_ref
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String base_image_ref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.architecture
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String architecture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.os_distro
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String os_distro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.os_version
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String os_version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer job_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.id
     *
     * @return the value of images.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.id
     *
     * @param id the value for images.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.created_at
     *
     * @return the value of images.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.created_at
     *
     * @param created_at the value for images.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.updated_at
     *
     * @return the value of images.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.updated_at
     *
     * @param updated_at the value for images.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.name
     *
     * @return the value of images.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.name
     *
     * @param name the value for images.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.image_uuid
     *
     * @return the value of images.image_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getImage_uuid() {
        return image_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.image_uuid
     *
     * @param image_uuid the value for images.image_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setImage_uuid(String image_uuid) {
        this.image_uuid = image_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.disk_format
     *
     * @return the value of images.disk_format
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDisk_format() {
        return disk_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.disk_format
     *
     * @param disk_format the value for images.disk_format
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDisk_format(String disk_format) {
        this.disk_format = disk_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.container_format
     *
     * @return the value of images.container_format
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getContainer_format() {
        return container_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.container_format
     *
     * @param container_format the value for images.container_format
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setContainer_format(String container_format) {
        this.container_format = container_format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.size
     *
     * @return the value of images.size
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.size
     *
     * @param size the value for images.size
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.status
     *
     * @return the value of images.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.status
     *
     * @param status the value for images.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.is_public
     *
     * @return the value of images.is_public
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Boolean getIs_public() {
        return is_public;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.is_public
     *
     * @param is_public the value for images.is_public
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setIs_public(Boolean is_public) {
        this.is_public = is_public;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.min_disk
     *
     * @return the value of images.min_disk
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getMin_disk() {
        return min_disk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.min_disk
     *
     * @param min_disk the value for images.min_disk
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setMin_disk(Integer min_disk) {
        this.min_disk = min_disk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.min_ram
     *
     * @return the value of images.min_ram
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getMin_ram() {
        return min_ram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.min_ram
     *
     * @param min_ram the value for images.min_ram
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setMin_ram(Integer min_ram) {
        this.min_ram = min_ram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.base_image_ref
     *
     * @return the value of images.base_image_ref
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getBase_image_ref() {
        return base_image_ref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.base_image_ref
     *
     * @param base_image_ref the value for images.base_image_ref
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setBase_image_ref(String base_image_ref) {
        this.base_image_ref = base_image_ref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.architecture
     *
     * @return the value of images.architecture
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getArchitecture() {
        return architecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.architecture
     *
     * @param architecture the value for images.architecture
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setArchitecture(String architecture) {
        this.architecture = architecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.os_distro
     *
     * @return the value of images.os_distro
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getOs_distro() {
        return os_distro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.os_distro
     *
     * @param os_distro the value for images.os_distro
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOs_distro(String os_distro) {
        this.os_distro = os_distro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.os_version
     *
     * @return the value of images.os_version
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getOs_version() {
        return os_version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.os_version
     *
     * @param os_version the value for images.os_version
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOs_version(String os_version) {
        this.os_version = os_version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.owner_id
     *
     * @return the value of images.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.owner_id
     *
     * @param owner_id the value for images.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.creator_id
     *
     * @return the value of images.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.creator_id
     *
     * @param creator_id the value for images.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.job_id
     *
     * @return the value of images.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.job_id
     *
     * @param job_id the value for images.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.description
     *
     * @return the value of images.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.description
     *
     * @param description the value for images.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}