package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBInstanceBackups {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance_backups.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance_backups.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance_backups.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance_backups.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance_backups.backup_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String backup_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance_backups.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance_backups.size
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance_backups.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer instance_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance_backups.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance_backups.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance_backups.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer job_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance_backups.id
     *
     * @return the value of instance_backups.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance_backups.id
     *
     * @param id the value for instance_backups.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance_backups.created_at
     *
     * @return the value of instance_backups.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance_backups.created_at
     *
     * @param created_at the value for instance_backups.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance_backups.updated_at
     *
     * @return the value of instance_backups.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance_backups.updated_at
     *
     * @param updated_at the value for instance_backups.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance_backups.name
     *
     * @return the value of instance_backups.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance_backups.name
     *
     * @param name the value for instance_backups.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance_backups.backup_uuid
     *
     * @return the value of instance_backups.backup_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getBackup_uuid() {
        return backup_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance_backups.backup_uuid
     *
     * @param backup_uuid the value for instance_backups.backup_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setBackup_uuid(String backup_uuid) {
        this.backup_uuid = backup_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance_backups.status
     *
     * @return the value of instance_backups.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance_backups.status
     *
     * @param status the value for instance_backups.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance_backups.size
     *
     * @return the value of instance_backups.size
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance_backups.size
     *
     * @param size the value for instance_backups.size
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance_backups.instance_id
     *
     * @return the value of instance_backups.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getInstance_id() {
        return instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance_backups.instance_id
     *
     * @param instance_id the value for instance_backups.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setInstance_id(Integer instance_id) {
        this.instance_id = instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance_backups.owner_id
     *
     * @return the value of instance_backups.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance_backups.owner_id
     *
     * @param owner_id the value for instance_backups.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance_backups.creator_id
     *
     * @return the value of instance_backups.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance_backups.creator_id
     *
     * @param creator_id the value for instance_backups.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance_backups.job_id
     *
     * @return the value of instance_backups.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance_backups.job_id
     *
     * @param job_id the value for instance_backups.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }
}