package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBInstances {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.instance_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String instance_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.display_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String display_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.vm_state
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String vm_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.task_state
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String task_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.memory_mb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer memory_mb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.vcpus
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer vcpus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.root_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer root_gb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.ephemeral_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer ephemeral_gb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.iops
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer iops;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.image_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer image_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.flavor_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer flavor_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.availability_zone
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String availability_zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.compute_node_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer compute_node_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer job_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instances.display_description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String display_description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.id
     *
     * @return the value of instances.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.id
     *
     * @param id the value for instances.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.created_at
     *
     * @return the value of instances.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.created_at
     *
     * @param created_at the value for instances.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.updated_at
     *
     * @return the value of instances.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.updated_at
     *
     * @param updated_at the value for instances.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.instance_uuid
     *
     * @return the value of instances.instance_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getInstance_uuid() {
        return instance_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.instance_uuid
     *
     * @param instance_uuid the value for instances.instance_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setInstance_uuid(String instance_uuid) {
        this.instance_uuid = instance_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.display_name
     *
     * @return the value of instances.display_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDisplay_name() {
        return display_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.display_name
     *
     * @param display_name the value for instances.display_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDisplay_name(String display_name) {
        this.display_name = display_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.vm_state
     *
     * @return the value of instances.vm_state
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getVm_state() {
        return vm_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.vm_state
     *
     * @param vm_state the value for instances.vm_state
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setVm_state(String vm_state) {
        this.vm_state = vm_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.task_state
     *
     * @return the value of instances.task_state
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getTask_state() {
        return task_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.task_state
     *
     * @param task_state the value for instances.task_state
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setTask_state(String task_state) {
        this.task_state = task_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.memory_mb
     *
     * @return the value of instances.memory_mb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getMemory_mb() {
        return memory_mb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.memory_mb
     *
     * @param memory_mb the value for instances.memory_mb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setMemory_mb(Integer memory_mb) {
        this.memory_mb = memory_mb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.vcpus
     *
     * @return the value of instances.vcpus
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getVcpus() {
        return vcpus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.vcpus
     *
     * @param vcpus the value for instances.vcpus
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setVcpus(Integer vcpus) {
        this.vcpus = vcpus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.root_gb
     *
     * @return the value of instances.root_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getRoot_gb() {
        return root_gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.root_gb
     *
     * @param root_gb the value for instances.root_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setRoot_gb(Integer root_gb) {
        this.root_gb = root_gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.ephemeral_gb
     *
     * @return the value of instances.ephemeral_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getEphemeral_gb() {
        return ephemeral_gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.ephemeral_gb
     *
     * @param ephemeral_gb the value for instances.ephemeral_gb
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setEphemeral_gb(Integer ephemeral_gb) {
        this.ephemeral_gb = ephemeral_gb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.iops
     *
     * @return the value of instances.iops
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getIops() {
        return iops;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.iops
     *
     * @param iops the value for instances.iops
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setIops(Integer iops) {
        this.iops = iops;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.image_id
     *
     * @return the value of instances.image_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getImage_id() {
        return image_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.image_id
     *
     * @param image_id the value for instances.image_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setImage_id(Integer image_id) {
        this.image_id = image_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.flavor_id
     *
     * @return the value of instances.flavor_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getFlavor_id() {
        return flavor_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.flavor_id
     *
     * @param flavor_id the value for instances.flavor_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setFlavor_id(Integer flavor_id) {
        this.flavor_id = flavor_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.availability_zone
     *
     * @return the value of instances.availability_zone
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getAvailability_zone() {
        return availability_zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.availability_zone
     *
     * @param availability_zone the value for instances.availability_zone
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setAvailability_zone(String availability_zone) {
        this.availability_zone = availability_zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.compute_node_id
     *
     * @return the value of instances.compute_node_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCompute_node_id() {
        return compute_node_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.compute_node_id
     *
     * @param compute_node_id the value for instances.compute_node_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCompute_node_id(Integer compute_node_id) {
        this.compute_node_id = compute_node_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.owner_id
     *
     * @return the value of instances.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.owner_id
     *
     * @param owner_id the value for instances.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.creator_id
     *
     * @return the value of instances.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.creator_id
     *
     * @param creator_id the value for instances.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.job_id
     *
     * @return the value of instances.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.job_id
     *
     * @param job_id the value for instances.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instances.display_description
     *
     * @return the value of instances.display_description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDisplay_description() {
        return display_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instances.display_description
     *
     * @param display_description the value for instances.display_description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDisplay_description(String display_description) {
        this.display_description = display_description;
    }
}