package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBJobs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.resource_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer resource_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.resource_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String resource_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.resource_type
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String resource_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.book_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String book_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.flow_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String flow_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.flow_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String flow_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.state
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs.state_desc
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String state_desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.id
     *
     * @return the value of jobs.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.id
     *
     * @param id the value for jobs.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.created_at
     *
     * @return the value of jobs.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.created_at
     *
     * @param created_at the value for jobs.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.updated_at
     *
     * @return the value of jobs.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.updated_at
     *
     * @param updated_at the value for jobs.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.resource_id
     *
     * @return the value of jobs.resource_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getResource_id() {
        return resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.resource_id
     *
     * @param resource_id the value for jobs.resource_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setResource_id(Integer resource_id) {
        this.resource_id = resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.resource_name
     *
     * @return the value of jobs.resource_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getResource_name() {
        return resource_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.resource_name
     *
     * @param resource_name the value for jobs.resource_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setResource_name(String resource_name) {
        this.resource_name = resource_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.resource_type
     *
     * @return the value of jobs.resource_type
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getResource_type() {
        return resource_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.resource_type
     *
     * @param resource_type the value for jobs.resource_type
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setResource_type(String resource_type) {
        this.resource_type = resource_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.book_uuid
     *
     * @return the value of jobs.book_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getBook_uuid() {
        return book_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.book_uuid
     *
     * @param book_uuid the value for jobs.book_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setBook_uuid(String book_uuid) {
        this.book_uuid = book_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.flow_uuid
     *
     * @return the value of jobs.flow_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getFlow_uuid() {
        return flow_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.flow_uuid
     *
     * @param flow_uuid the value for jobs.flow_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setFlow_uuid(String flow_uuid) {
        this.flow_uuid = flow_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.flow_name
     *
     * @return the value of jobs.flow_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getFlow_name() {
        return flow_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.flow_name
     *
     * @param flow_name the value for jobs.flow_name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setFlow_name(String flow_name) {
        this.flow_name = flow_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.state
     *
     * @return the value of jobs.state
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.state
     *
     * @param state the value for jobs.state
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.owner_id
     *
     * @return the value of jobs.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.owner_id
     *
     * @param owner_id the value for jobs.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.creator_id
     *
     * @return the value of jobs.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.creator_id
     *
     * @param creator_id the value for jobs.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs.state_desc
     *
     * @return the value of jobs.state_desc
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getState_desc() {
        return state_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs.state_desc
     *
     * @param state_desc the value for jobs.state_desc
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setState_desc(String state_desc) {
        this.state_desc = state_desc;
    }
}