package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBLbPoolStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_pool_statistics.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_pool_statistics.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_pool_statistics.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_pool_statistics.lb_pool_statistic_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String lb_pool_statistic_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_pool_statistics.bytes_in
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Long bytes_in;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_pool_statistics.bytes_out
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Long bytes_out;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_pool_statistics.active_connections
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Long active_connections;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_pool_statistics.total_connections
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Long total_connections;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_pool_statistics.lb_pool_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer lb_pool_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_pool_statistics.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_pool_statistics.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_pool_statistics.id
     *
     * @return the value of lb_pool_statistics.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_pool_statistics.id
     *
     * @param id the value for lb_pool_statistics.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_pool_statistics.created_at
     *
     * @return the value of lb_pool_statistics.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_pool_statistics.created_at
     *
     * @param created_at the value for lb_pool_statistics.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_pool_statistics.updated_at
     *
     * @return the value of lb_pool_statistics.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_pool_statistics.updated_at
     *
     * @param updated_at the value for lb_pool_statistics.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_pool_statistics.lb_pool_statistic_uuid
     *
     * @return the value of lb_pool_statistics.lb_pool_statistic_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getLb_pool_statistic_uuid() {
        return lb_pool_statistic_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_pool_statistics.lb_pool_statistic_uuid
     *
     * @param lb_pool_statistic_uuid the value for lb_pool_statistics.lb_pool_statistic_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setLb_pool_statistic_uuid(String lb_pool_statistic_uuid) {
        this.lb_pool_statistic_uuid = lb_pool_statistic_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_pool_statistics.bytes_in
     *
     * @return the value of lb_pool_statistics.bytes_in
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Long getBytes_in() {
        return bytes_in;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_pool_statistics.bytes_in
     *
     * @param bytes_in the value for lb_pool_statistics.bytes_in
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setBytes_in(Long bytes_in) {
        this.bytes_in = bytes_in;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_pool_statistics.bytes_out
     *
     * @return the value of lb_pool_statistics.bytes_out
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Long getBytes_out() {
        return bytes_out;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_pool_statistics.bytes_out
     *
     * @param bytes_out the value for lb_pool_statistics.bytes_out
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setBytes_out(Long bytes_out) {
        this.bytes_out = bytes_out;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_pool_statistics.active_connections
     *
     * @return the value of lb_pool_statistics.active_connections
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Long getActive_connections() {
        return active_connections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_pool_statistics.active_connections
     *
     * @param active_connections the value for lb_pool_statistics.active_connections
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setActive_connections(Long active_connections) {
        this.active_connections = active_connections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_pool_statistics.total_connections
     *
     * @return the value of lb_pool_statistics.total_connections
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Long getTotal_connections() {
        return total_connections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_pool_statistics.total_connections
     *
     * @param total_connections the value for lb_pool_statistics.total_connections
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setTotal_connections(Long total_connections) {
        this.total_connections = total_connections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_pool_statistics.lb_pool_id
     *
     * @return the value of lb_pool_statistics.lb_pool_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getLb_pool_id() {
        return lb_pool_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_pool_statistics.lb_pool_id
     *
     * @param lb_pool_id the value for lb_pool_statistics.lb_pool_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setLb_pool_id(Integer lb_pool_id) {
        this.lb_pool_id = lb_pool_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_pool_statistics.owner_id
     *
     * @return the value of lb_pool_statistics.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_pool_statistics.owner_id
     *
     * @param owner_id the value for lb_pool_statistics.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_pool_statistics.creator_id
     *
     * @return the value of lb_pool_statistics.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_pool_statistics.creator_id
     *
     * @param creator_id the value for lb_pool_statistics.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }
}