package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBLbVips {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.lb_vip_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String lb_vip_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.connection_limit
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer connection_limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.protocol
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.protocol_port
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer protocol_port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.port_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer port_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lb_vips.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.id
     *
     * @return the value of lb_vips.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.id
     *
     * @param id the value for lb_vips.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.created_at
     *
     * @return the value of lb_vips.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.created_at
     *
     * @param created_at the value for lb_vips.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.updated_at
     *
     * @return the value of lb_vips.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.updated_at
     *
     * @param updated_at the value for lb_vips.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.lb_vip_uuid
     *
     * @return the value of lb_vips.lb_vip_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getLb_vip_uuid() {
        return lb_vip_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.lb_vip_uuid
     *
     * @param lb_vip_uuid the value for lb_vips.lb_vip_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setLb_vip_uuid(String lb_vip_uuid) {
        this.lb_vip_uuid = lb_vip_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.name
     *
     * @return the value of lb_vips.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.name
     *
     * @param name the value for lb_vips.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.connection_limit
     *
     * @return the value of lb_vips.connection_limit
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getConnection_limit() {
        return connection_limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.connection_limit
     *
     * @param connection_limit the value for lb_vips.connection_limit
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setConnection_limit(Integer connection_limit) {
        this.connection_limit = connection_limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.protocol
     *
     * @return the value of lb_vips.protocol
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.protocol
     *
     * @param protocol the value for lb_vips.protocol
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.protocol_port
     *
     * @return the value of lb_vips.protocol_port
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getProtocol_port() {
        return protocol_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.protocol_port
     *
     * @param protocol_port the value for lb_vips.protocol_port
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setProtocol_port(Integer protocol_port) {
        this.protocol_port = protocol_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.port_id
     *
     * @return the value of lb_vips.port_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getPort_id() {
        return port_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.port_id
     *
     * @param port_id the value for lb_vips.port_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setPort_id(Integer port_id) {
        this.port_id = port_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.owner_id
     *
     * @return the value of lb_vips.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.owner_id
     *
     * @param owner_id the value for lb_vips.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.creator_id
     *
     * @return the value of lb_vips.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.creator_id
     *
     * @param creator_id the value for lb_vips.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lb_vips.description
     *
     * @return the value of lb_vips.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lb_vips.description
     *
     * @param description the value for lb_vips.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}