package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBPermissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.view
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String view;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.method
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.id
     *
     * @return the value of permissions.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.id
     *
     * @param id the value for permissions.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.created_at
     *
     * @return the value of permissions.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.created_at
     *
     * @param created_at the value for permissions.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.updated_at
     *
     * @return the value of permissions.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.updated_at
     *
     * @param updated_at the value for permissions.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.name
     *
     * @return the value of permissions.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.name
     *
     * @param name the value for permissions.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.view
     *
     * @return the value of permissions.view
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getView() {
        return view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.view
     *
     * @param view the value for permissions.view
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setView(String view) {
        this.view = view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.method
     *
     * @return the value of permissions.method
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.method
     *
     * @param method the value for permissions.method
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.description
     *
     * @return the value of permissions.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.description
     *
     * @param description the value for permissions.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}