package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBPorts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.port_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String port_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.mac_address
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String mac_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.bandwidth_rx
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer bandwidth_rx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.bandwidth_tx
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer bandwidth_tx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.mtu
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer mtu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.device_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String device_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.device_owner
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String device_owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.network_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer network_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.subnet_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer subnet_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer instance_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ports.fixed_ips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String fixed_ips;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.id
     *
     * @return the value of ports.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.id
     *
     * @param id the value for ports.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.created_at
     *
     * @return the value of ports.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.created_at
     *
     * @param created_at the value for ports.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.updated_at
     *
     * @return the value of ports.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.updated_at
     *
     * @param updated_at the value for ports.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.port_uuid
     *
     * @return the value of ports.port_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getPort_uuid() {
        return port_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.port_uuid
     *
     * @param port_uuid the value for ports.port_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setPort_uuid(String port_uuid) {
        this.port_uuid = port_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.name
     *
     * @return the value of ports.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.name
     *
     * @param name the value for ports.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.status
     *
     * @return the value of ports.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.status
     *
     * @param status the value for ports.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.mac_address
     *
     * @return the value of ports.mac_address
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getMac_address() {
        return mac_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.mac_address
     *
     * @param mac_address the value for ports.mac_address
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setMac_address(String mac_address) {
        this.mac_address = mac_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.bandwidth_rx
     *
     * @return the value of ports.bandwidth_rx
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getBandwidth_rx() {
        return bandwidth_rx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.bandwidth_rx
     *
     * @param bandwidth_rx the value for ports.bandwidth_rx
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setBandwidth_rx(Integer bandwidth_rx) {
        this.bandwidth_rx = bandwidth_rx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.bandwidth_tx
     *
     * @return the value of ports.bandwidth_tx
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getBandwidth_tx() {
        return bandwidth_tx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.bandwidth_tx
     *
     * @param bandwidth_tx the value for ports.bandwidth_tx
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setBandwidth_tx(Integer bandwidth_tx) {
        this.bandwidth_tx = bandwidth_tx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.mtu
     *
     * @return the value of ports.mtu
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getMtu() {
        return mtu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.mtu
     *
     * @param mtu the value for ports.mtu
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setMtu(Integer mtu) {
        this.mtu = mtu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.device_id
     *
     * @return the value of ports.device_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDevice_id() {
        return device_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.device_id
     *
     * @param device_id the value for ports.device_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDevice_id(String device_id) {
        this.device_id = device_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.device_owner
     *
     * @return the value of ports.device_owner
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDevice_owner() {
        return device_owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.device_owner
     *
     * @param device_owner the value for ports.device_owner
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDevice_owner(String device_owner) {
        this.device_owner = device_owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.network_id
     *
     * @return the value of ports.network_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getNetwork_id() {
        return network_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.network_id
     *
     * @param network_id the value for ports.network_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setNetwork_id(Integer network_id) {
        this.network_id = network_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.subnet_id
     *
     * @return the value of ports.subnet_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getSubnet_id() {
        return subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.subnet_id
     *
     * @param subnet_id the value for ports.subnet_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setSubnet_id(Integer subnet_id) {
        this.subnet_id = subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.instance_id
     *
     * @return the value of ports.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getInstance_id() {
        return instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.instance_id
     *
     * @param instance_id the value for ports.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setInstance_id(Integer instance_id) {
        this.instance_id = instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.owner_id
     *
     * @return the value of ports.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.owner_id
     *
     * @param owner_id the value for ports.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.creator_id
     *
     * @return the value of ports.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.creator_id
     *
     * @param creator_id the value for ports.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ports.fixed_ips
     *
     * @return the value of ports.fixed_ips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getFixed_ips() {
        return fixed_ips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ports.fixed_ips
     *
     * @param fixed_ips the value for ports.fixed_ips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setFixed_ips(String fixed_ips) {
        this.fixed_ips = fixed_ips;
    }
}