package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBQuotas {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotas.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotas.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotas.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotas.user_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotas.resource
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotas.hard_limit
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer hard_limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotas.id
     *
     * @return the value of quotas.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotas.id
     *
     * @param id the value for quotas.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotas.created_at
     *
     * @return the value of quotas.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotas.created_at
     *
     * @param created_at the value for quotas.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotas.updated_at
     *
     * @return the value of quotas.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotas.updated_at
     *
     * @param updated_at the value for quotas.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotas.user_id
     *
     * @return the value of quotas.user_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotas.user_id
     *
     * @param user_id the value for quotas.user_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotas.resource
     *
     * @return the value of quotas.resource
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotas.resource
     *
     * @param resource the value for quotas.resource
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setResource(String resource) {
        this.resource = resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotas.hard_limit
     *
     * @return the value of quotas.hard_limit
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getHard_limit() {
        return hard_limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotas.hard_limit
     *
     * @param hard_limit the value for quotas.hard_limit
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setHard_limit(Integer hard_limit) {
        this.hard_limit = hard_limit;
    }
}