package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBReservations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.usage_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer usage_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.user_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.resource
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.delta
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer delta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.expire
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date expire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservations.deleted
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.id
     *
     * @return the value of reservations.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.id
     *
     * @param id the value for reservations.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.created_at
     *
     * @return the value of reservations.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.created_at
     *
     * @param created_at the value for reservations.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.updated_at
     *
     * @return the value of reservations.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.updated_at
     *
     * @param updated_at the value for reservations.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.uuid
     *
     * @return the value of reservations.uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.uuid
     *
     * @param uuid the value for reservations.uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.usage_id
     *
     * @return the value of reservations.usage_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getUsage_id() {
        return usage_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.usage_id
     *
     * @param usage_id the value for reservations.usage_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUsage_id(Integer usage_id) {
        this.usage_id = usage_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.user_id
     *
     * @return the value of reservations.user_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.user_id
     *
     * @param user_id the value for reservations.user_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.resource
     *
     * @return the value of reservations.resource
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.resource
     *
     * @param resource the value for reservations.resource
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setResource(String resource) {
        this.resource = resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.delta
     *
     * @return the value of reservations.delta
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getDelta() {
        return delta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.delta
     *
     * @param delta the value for reservations.delta
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDelta(Integer delta) {
        this.delta = delta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.expire
     *
     * @return the value of reservations.expire
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.expire
     *
     * @param expire the value for reservations.expire
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setExpire(Date expire) {
        this.expire = expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservations.deleted
     *
     * @return the value of reservations.deleted
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservations.deleted
     *
     * @param deleted the value for reservations.deleted
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}