package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBRouters {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routers.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routers.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routers.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routers.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routers.admin_state_up
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Boolean admin_state_up;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routers.router_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String router_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routers.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routers.cidr
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String cidr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routers.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routers.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routers.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer job_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routers.id
     *
     * @return the value of routers.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routers.id
     *
     * @param id the value for routers.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routers.created_at
     *
     * @return the value of routers.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routers.created_at
     *
     * @param created_at the value for routers.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routers.updated_at
     *
     * @return the value of routers.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routers.updated_at
     *
     * @param updated_at the value for routers.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routers.name
     *
     * @return the value of routers.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routers.name
     *
     * @param name the value for routers.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routers.admin_state_up
     *
     * @return the value of routers.admin_state_up
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Boolean getAdmin_state_up() {
        return admin_state_up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routers.admin_state_up
     *
     * @param admin_state_up the value for routers.admin_state_up
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setAdmin_state_up(Boolean admin_state_up) {
        this.admin_state_up = admin_state_up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routers.router_uuid
     *
     * @return the value of routers.router_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getRouter_uuid() {
        return router_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routers.router_uuid
     *
     * @param router_uuid the value for routers.router_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setRouter_uuid(String router_uuid) {
        this.router_uuid = router_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routers.status
     *
     * @return the value of routers.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routers.status
     *
     * @param status the value for routers.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routers.cidr
     *
     * @return the value of routers.cidr
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getCidr() {
        return cidr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routers.cidr
     *
     * @param cidr the value for routers.cidr
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCidr(String cidr) {
        this.cidr = cidr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routers.owner_id
     *
     * @return the value of routers.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routers.owner_id
     *
     * @param owner_id the value for routers.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routers.creator_id
     *
     * @return the value of routers.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routers.creator_id
     *
     * @param creator_id the value for routers.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routers.job_id
     *
     * @return the value of routers.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routers.job_id
     *
     * @param job_id the value for routers.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }
}