package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBSubnets {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.subnet_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String subnet_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.ip_version
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String ip_version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.cidr
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String cidr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.gateway_ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String gateway_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.enable_dhcp
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Boolean enable_dhcp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.network_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer network_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnets.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.id
     *
     * @return the value of subnets.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.id
     *
     * @param id the value for subnets.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.created_at
     *
     * @return the value of subnets.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.created_at
     *
     * @param created_at the value for subnets.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.updated_at
     *
     * @return the value of subnets.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.updated_at
     *
     * @param updated_at the value for subnets.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.subnet_uuid
     *
     * @return the value of subnets.subnet_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getSubnet_uuid() {
        return subnet_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.subnet_uuid
     *
     * @param subnet_uuid the value for subnets.subnet_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setSubnet_uuid(String subnet_uuid) {
        this.subnet_uuid = subnet_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.name
     *
     * @return the value of subnets.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.name
     *
     * @param name the value for subnets.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.ip_version
     *
     * @return the value of subnets.ip_version
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getIp_version() {
        return ip_version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.ip_version
     *
     * @param ip_version the value for subnets.ip_version
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setIp_version(String ip_version) {
        this.ip_version = ip_version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.cidr
     *
     * @return the value of subnets.cidr
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getCidr() {
        return cidr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.cidr
     *
     * @param cidr the value for subnets.cidr
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCidr(String cidr) {
        this.cidr = cidr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.gateway_ip
     *
     * @return the value of subnets.gateway_ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getGateway_ip() {
        return gateway_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.gateway_ip
     *
     * @param gateway_ip the value for subnets.gateway_ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setGateway_ip(String gateway_ip) {
        this.gateway_ip = gateway_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.enable_dhcp
     *
     * @return the value of subnets.enable_dhcp
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Boolean getEnable_dhcp() {
        return enable_dhcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.enable_dhcp
     *
     * @param enable_dhcp the value for subnets.enable_dhcp
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setEnable_dhcp(Boolean enable_dhcp) {
        this.enable_dhcp = enable_dhcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.network_id
     *
     * @return the value of subnets.network_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getNetwork_id() {
        return network_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.network_id
     *
     * @param network_id the value for subnets.network_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setNetwork_id(Integer network_id) {
        this.network_id = network_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.owner_id
     *
     * @return the value of subnets.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.owner_id
     *
     * @param owner_id the value for subnets.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnets.creator_id
     *
     * @return the value of subnets.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnets.creator_id
     *
     * @param creator_id the value for subnets.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }
}