package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBUserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.user_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.browser
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String browser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.remark
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.id
     *
     * @return the value of user_login.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.id
     *
     * @param id the value for user_login.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.created_at
     *
     * @return the value of user_login.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.created_at
     *
     * @param created_at the value for user_login.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.updated_at
     *
     * @return the value of user_login.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.updated_at
     *
     * @param updated_at the value for user_login.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.ip
     *
     * @return the value of user_login.ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.ip
     *
     * @param ip the value for user_login.ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.user_id
     *
     * @return the value of user_login.user_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.user_id
     *
     * @param user_id the value for user_login.user_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.browser
     *
     * @return the value of user_login.browser
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.browser
     *
     * @param browser the value for user_login.browser
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setBrowser(String browser) {
        this.browser = browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.remark
     *
     * @return the value of user_login.remark
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.remark
     *
     * @param remark the value for user_login.remark
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}