package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBVirtualrouterFloatingips {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.floatingip_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String floatingip_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.floating_ip_address
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String floating_ip_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.floating_network_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer floating_network_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.fixed_port_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String fixed_port_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.fixed_ip_address
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String fixed_ip_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.virtualrouter_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer virtualrouter_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_floatingips.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer job_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.id
     *
     * @return the value of virtualrouter_floatingips.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.id
     *
     * @param id the value for virtualrouter_floatingips.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.created_at
     *
     * @return the value of virtualrouter_floatingips.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.created_at
     *
     * @param created_at the value for virtualrouter_floatingips.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.updated_at
     *
     * @return the value of virtualrouter_floatingips.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.updated_at
     *
     * @param updated_at the value for virtualrouter_floatingips.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.floatingip_uuid
     *
     * @return the value of virtualrouter_floatingips.floatingip_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getFloatingip_uuid() {
        return floatingip_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.floatingip_uuid
     *
     * @param floatingip_uuid the value for virtualrouter_floatingips.floatingip_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setFloatingip_uuid(String floatingip_uuid) {
        this.floatingip_uuid = floatingip_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.floating_ip_address
     *
     * @return the value of virtualrouter_floatingips.floating_ip_address
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getFloating_ip_address() {
        return floating_ip_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.floating_ip_address
     *
     * @param floating_ip_address the value for virtualrouter_floatingips.floating_ip_address
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setFloating_ip_address(String floating_ip_address) {
        this.floating_ip_address = floating_ip_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.floating_network_id
     *
     * @return the value of virtualrouter_floatingips.floating_network_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getFloating_network_id() {
        return floating_network_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.floating_network_id
     *
     * @param floating_network_id the value for virtualrouter_floatingips.floating_network_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setFloating_network_id(Integer floating_network_id) {
        this.floating_network_id = floating_network_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.fixed_port_id
     *
     * @return the value of virtualrouter_floatingips.fixed_port_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getFixed_port_id() {
        return fixed_port_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.fixed_port_id
     *
     * @param fixed_port_id the value for virtualrouter_floatingips.fixed_port_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setFixed_port_id(String fixed_port_id) {
        this.fixed_port_id = fixed_port_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.fixed_ip_address
     *
     * @return the value of virtualrouter_floatingips.fixed_ip_address
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getFixed_ip_address() {
        return fixed_ip_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.fixed_ip_address
     *
     * @param fixed_ip_address the value for virtualrouter_floatingips.fixed_ip_address
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setFixed_ip_address(String fixed_ip_address) {
        this.fixed_ip_address = fixed_ip_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.virtualrouter_id
     *
     * @return the value of virtualrouter_floatingips.virtualrouter_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getVirtualrouter_id() {
        return virtualrouter_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.virtualrouter_id
     *
     * @param virtualrouter_id the value for virtualrouter_floatingips.virtualrouter_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setVirtualrouter_id(Integer virtualrouter_id) {
        this.virtualrouter_id = virtualrouter_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.status
     *
     * @return the value of virtualrouter_floatingips.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.status
     *
     * @param status the value for virtualrouter_floatingips.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.owner_id
     *
     * @return the value of virtualrouter_floatingips.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.owner_id
     *
     * @param owner_id the value for virtualrouter_floatingips.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.creator_id
     *
     * @return the value of virtualrouter_floatingips.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.creator_id
     *
     * @param creator_id the value for virtualrouter_floatingips.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_floatingips.job_id
     *
     * @return the value of virtualrouter_floatingips.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_floatingips.job_id
     *
     * @param job_id the value for virtualrouter_floatingips.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }
}