package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBVirtualrouterNats {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_nats.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_nats.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_nats.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_nats.virtualrouter_nat_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String virtualrouter_nat_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_nats.proto
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String proto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_nats.src_port
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer src_port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_nats.dest_ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String dest_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_nats.dest_port
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer dest_port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_nats.floatingip_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer floatingip_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_nats.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virtualrouter_nats.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_nats.id
     *
     * @return the value of virtualrouter_nats.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_nats.id
     *
     * @param id the value for virtualrouter_nats.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_nats.created_at
     *
     * @return the value of virtualrouter_nats.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_nats.created_at
     *
     * @param created_at the value for virtualrouter_nats.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_nats.updated_at
     *
     * @return the value of virtualrouter_nats.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_nats.updated_at
     *
     * @param updated_at the value for virtualrouter_nats.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_nats.virtualrouter_nat_uuid
     *
     * @return the value of virtualrouter_nats.virtualrouter_nat_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getVirtualrouter_nat_uuid() {
        return virtualrouter_nat_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_nats.virtualrouter_nat_uuid
     *
     * @param virtualrouter_nat_uuid the value for virtualrouter_nats.virtualrouter_nat_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setVirtualrouter_nat_uuid(String virtualrouter_nat_uuid) {
        this.virtualrouter_nat_uuid = virtualrouter_nat_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_nats.proto
     *
     * @return the value of virtualrouter_nats.proto
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getProto() {
        return proto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_nats.proto
     *
     * @param proto the value for virtualrouter_nats.proto
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setProto(String proto) {
        this.proto = proto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_nats.src_port
     *
     * @return the value of virtualrouter_nats.src_port
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getSrc_port() {
        return src_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_nats.src_port
     *
     * @param src_port the value for virtualrouter_nats.src_port
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setSrc_port(Integer src_port) {
        this.src_port = src_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_nats.dest_ip
     *
     * @return the value of virtualrouter_nats.dest_ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDest_ip() {
        return dest_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_nats.dest_ip
     *
     * @param dest_ip the value for virtualrouter_nats.dest_ip
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDest_ip(String dest_ip) {
        this.dest_ip = dest_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_nats.dest_port
     *
     * @return the value of virtualrouter_nats.dest_port
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getDest_port() {
        return dest_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_nats.dest_port
     *
     * @param dest_port the value for virtualrouter_nats.dest_port
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDest_port(Integer dest_port) {
        this.dest_port = dest_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_nats.floatingip_id
     *
     * @return the value of virtualrouter_nats.floatingip_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getFloatingip_id() {
        return floatingip_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_nats.floatingip_id
     *
     * @param floatingip_id the value for virtualrouter_nats.floatingip_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setFloatingip_id(Integer floatingip_id) {
        this.floatingip_id = floatingip_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_nats.owner_id
     *
     * @return the value of virtualrouter_nats.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_nats.owner_id
     *
     * @param owner_id the value for virtualrouter_nats.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virtualrouter_nats.creator_id
     *
     * @return the value of virtualrouter_nats.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virtualrouter_nats.creator_id
     *
     * @param creator_id the value for virtualrouter_nats.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }
}