package com.culabs.unicomportal.model.db;

import java.util.Date;

public class DBVolumes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date created_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date updated_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.volume_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String volume_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.size
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.attach_time
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Date attach_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.Bootable
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Boolean bootable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer instance_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer owner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private Integer job_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volumes.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.id
     *
     * @return the value of volumes.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.id
     *
     * @param id the value for volumes.id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.created_at
     *
     * @return the value of volumes.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.created_at
     *
     * @param created_at the value for volumes.created_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.updated_at
     *
     * @return the value of volumes.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.updated_at
     *
     * @param updated_at the value for volumes.updated_at
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.name
     *
     * @return the value of volumes.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.name
     *
     * @param name the value for volumes.name
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.volume_uuid
     *
     * @return the value of volumes.volume_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getVolume_uuid() {
        return volume_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.volume_uuid
     *
     * @param volume_uuid the value for volumes.volume_uuid
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setVolume_uuid(String volume_uuid) {
        this.volume_uuid = volume_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.size
     *
     * @return the value of volumes.size
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.size
     *
     * @param size the value for volumes.size
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.status
     *
     * @return the value of volumes.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.status
     *
     * @param status the value for volumes.status
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.attach_time
     *
     * @return the value of volumes.attach_time
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Date getAttach_time() {
        return attach_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.attach_time
     *
     * @param attach_time the value for volumes.attach_time
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setAttach_time(Date attach_time) {
        this.attach_time = attach_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.Bootable
     *
     * @return the value of volumes.Bootable
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Boolean getBootable() {
        return bootable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.Bootable
     *
     * @param bootable the value for volumes.Bootable
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setBootable(Boolean bootable) {
        this.bootable = bootable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.instance_id
     *
     * @return the value of volumes.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getInstance_id() {
        return instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.instance_id
     *
     * @param instance_id the value for volumes.instance_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setInstance_id(Integer instance_id) {
        this.instance_id = instance_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.owner_id
     *
     * @return the value of volumes.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getOwner_id() {
        return owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.owner_id
     *
     * @param owner_id the value for volumes.owner_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setOwner_id(Integer owner_id) {
        this.owner_id = owner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.creator_id
     *
     * @return the value of volumes.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.creator_id
     *
     * @param creator_id the value for volumes.creator_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.job_id
     *
     * @return the value of volumes.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public Integer getJob_id() {
        return job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.job_id
     *
     * @param job_id the value for volumes.job_id
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setJob_id(Integer job_id) {
        this.job_id = job_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volumes.description
     *
     * @return the value of volumes.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volumes.description
     *
     * @param description the value for volumes.description
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}