//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.23 at 09:37:17 上午 CST 
//


package com.culabs.nfvo.model.vnfd;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.culabs.nfvo.model.vnfd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Provider_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "provider");
    private final static QName _NumInstances_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "num-instances");
    private final static QName _VduFlavorurId_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "vdu-flavorur-id");
    private final static QName _VnfFlavourId_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "vnf-flavour-id");
    private final static QName _VduId_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "vdu-id");
    private final static QName _Value_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "value");
    private final static QName _Key_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "key");
    private final static QName _Name_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "name");
    private final static QName _ParaId_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "para-id");
    private final static QName _VmImage_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "vm_image");
    private final static QName _Memory_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "memory");
    private final static QName _VnfdId_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "vnfd-id");
    private final static QName _Version_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "version");
    private final static QName _ConnectionPointRef_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "connection-point-ref");
    private final static QName _Description_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "description");
    private final static QName _Cpu_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "cpu");
    private final static QName _ParamId_QNAME = new QName("urn:com.culabs.nfvo.model.vnfd", "param-id");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.culabs.nfvo.model.vnfd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Vnfd }
     * 
     */
    public Vnfd createVnfd() {
        return new Vnfd();
    }

    /**
     * Create an instance of {@link Workflows }
     * 
     */
    public Workflows createWorkflows() {
        return new Workflows();
    }

    /**
     * Create an instance of {@link Init }
     * 
     */
    public Init createInit() {
        return new Init();
    }

    /**
     * Create an instance of {@link Terminate }
     * 
     */
    public Terminate createTerminate() {
        return new Terminate();
    }

    /**
     * Create an instance of {@link GracefulShutdown }
     * 
     */
    public GracefulShutdown createGracefulShutdown() {
        return new GracefulShutdown();
    }

    /**
     * Create an instance of {@link ConnectionPoints }
     * 
     */
    public ConnectionPoints createConnectionPoints() {
        return new ConnectionPoints();
    }

    /**
     * Create an instance of {@link ConnectionPoint }
     * 
     */
    public ConnectionPoint createConnectionPoint() {
        return new ConnectionPoint();
    }

    /**
     * Create an instance of {@link InternalConnectivity }
     * 
     */
    public InternalConnectivity createInternalConnectivity() {
        return new InternalConnectivity();
    }

    /**
     * Create an instance of {@link MonitoringParams }
     * 
     */
    public MonitoringParams createMonitoringParams() {
        return new MonitoringParams();
    }

    /**
     * Create an instance of {@link VnfFlavours }
     * 
     */
    public VnfFlavours createVnfFlavours() {
        return new VnfFlavours();
    }

    /**
     * Create an instance of {@link VnfFlavour }
     * 
     */
    public VnfFlavour createVnfFlavour() {
        return new VnfFlavour();
    }

    /**
     * Create an instance of {@link AssuranceParams }
     * 
     */
    public AssuranceParams createAssuranceParams() {
        return new AssuranceParams();
    }

    /**
     * Create an instance of {@link Vdus }
     * 
     */
    public Vdus createVdus() {
        return new Vdus();
    }

    /**
     * Create an instance of {@link Vdu }
     * 
     */
    public Vdu createVdu() {
        return new Vdu();
    }

    /**
     * Create an instance of {@link VduFlavour }
     * 
     */
    public VduFlavour createVduFlavour() {
        return new VduFlavour();
    }

    /**
     * Create an instance of {@link Storage }
     * 
     */
    public Storage createStorage() {
        return new Storage();
    }

    /**
     * Create an instance of {@link OtherConstraints }
     * 
     */
    public OtherConstraints createOtherConstraints() {
        return new OtherConstraints();
    }

    /**
     * Create an instance of {@link NetworkInterfaces }
     * 
     */
    public NetworkInterfaces createNetworkInterfaces() {
        return new NetworkInterfaces();
    }

    /**
     * Create an instance of {@link NetworkInterface }
     * 
     */
    public NetworkInterface createNetworkInterface() {
        return new NetworkInterface();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Dependencies }
     * 
     */
    public Dependencies createDependencies() {
        return new Dependencies();
    }

    /**
     * Create an instance of {@link AutoscalingPolicies }
     * 
     */
    public AutoscalingPolicies createAutoscalingPolicies() {
        return new AutoscalingPolicies();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "provider")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProvider(String value) {
        return new JAXBElement<String>(_Provider_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "num-instances")
    public JAXBElement<BigInteger> createNumInstances(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumInstances_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "vdu-flavorur-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVduFlavorurId(String value) {
        return new JAXBElement<String>(_VduFlavorurId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "vnf-flavour-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVnfFlavourId(String value) {
        return new JAXBElement<String>(_VnfFlavourId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "vdu-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVduId(String value) {
        return new JAXBElement<String>(_VduId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "value")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "key")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createKey(String value) {
        return new JAXBElement<String>(_Key_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "para-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createParaId(String value) {
        return new JAXBElement<String>(_ParaId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "vm_image")
    public JAXBElement<String> createVmImage(String value) {
        return new JAXBElement<String>(_VmImage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "memory")
    public JAXBElement<BigInteger> createMemory(BigInteger value) {
        return new JAXBElement<BigInteger>(_Memory_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "vnfd-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVnfdId(String value) {
        return new JAXBElement<String>(_VnfdId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "version")
    public JAXBElement<BigDecimal> createVersion(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Version_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "connection-point-ref")
    public JAXBElement<String> createConnectionPointRef(String value) {
        return new JAXBElement<String>(_ConnectionPointRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "cpu")
    public JAXBElement<BigInteger> createCpu(BigInteger value) {
        return new JAXBElement<BigInteger>(_Cpu_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:com.culabs.nfvo.model.vnfd", name = "param-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createParamId(String value) {
        return new JAXBElement<String>(_ParamId_QNAME, String.class, null, value);
    }

}
