//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.23 at 09:37:17 上午 CST 
//


package com.culabs.nfvo.model.vnfd;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}name"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}vnfd-id"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}provider"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}description"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}version"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}workflows"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}connection-points"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}internal-connectivity"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}monitoring-params"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}vnf-flavours"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}dependencies"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}autoscaling-policies"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "vnfdId",
    "provider",
    "description",
    "version",
    "workflows",
    "connectionPoints",
    "internalConnectivity",
    "monitoringParams",
    "vnfFlavours",
    "dependencies",
    "autoscalingPolicies"
})
@XmlRootElement(name = "vnfd")
public class Vnfd {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlElement(name = "vnfd-id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String vnfdId;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String provider;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected BigDecimal version;
    @XmlElement(required = true)
    protected Workflows workflows;
    @XmlElement(name = "connection-points", required = true)
    protected ConnectionPoints connectionPoints;
    @XmlElement(name = "internal-connectivity", required = true)
    protected InternalConnectivity internalConnectivity;
    @XmlElement(name = "monitoring-params", required = true)
    protected MonitoringParams monitoringParams;
    @XmlElement(name = "vnf-flavours", required = true)
    protected VnfFlavours vnfFlavours;
    @XmlElement(required = true)
    protected Dependencies dependencies;
    @XmlElement(name = "autoscaling-policies", required = true)
    protected AutoscalingPolicies autoscalingPolicies;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the vnfdId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnfdId() {
        return vnfdId;
    }

    /**
     * Sets the value of the vnfdId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnfdId(String value) {
        this.vnfdId = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the workflows property.
     * 
     * @return
     *     possible object is
     *     {@link Workflows }
     *     
     */
    public Workflows getWorkflows() {
        return workflows;
    }

    /**
     * Sets the value of the workflows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Workflows }
     *     
     */
    public void setWorkflows(Workflows value) {
        this.workflows = value;
    }

    /**
     * Gets the value of the connectionPoints property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionPoints }
     *     
     */
    public ConnectionPoints getConnectionPoints() {
        return connectionPoints;
    }

    /**
     * Sets the value of the connectionPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionPoints }
     *     
     */
    public void setConnectionPoints(ConnectionPoints value) {
        this.connectionPoints = value;
    }

    /**
     * Gets the value of the internalConnectivity property.
     * 
     * @return
     *     possible object is
     *     {@link InternalConnectivity }
     *     
     */
    public InternalConnectivity getInternalConnectivity() {
        return internalConnectivity;
    }

    /**
     * Sets the value of the internalConnectivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalConnectivity }
     *     
     */
    public void setInternalConnectivity(InternalConnectivity value) {
        this.internalConnectivity = value;
    }

    /**
     * Gets the value of the monitoringParams property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringParams }
     *     
     */
    public MonitoringParams getMonitoringParams() {
        return monitoringParams;
    }

    /**
     * Sets the value of the monitoringParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringParams }
     *     
     */
    public void setMonitoringParams(MonitoringParams value) {
        this.monitoringParams = value;
    }

    /**
     * Gets the value of the vnfFlavours property.
     * 
     * @return
     *     possible object is
     *     {@link VnfFlavours }
     *     
     */
    public VnfFlavours getVnfFlavours() {
        return vnfFlavours;
    }

    /**
     * Sets the value of the vnfFlavours property.
     * 
     * @param value
     *     allowed object is
     *     {@link VnfFlavours }
     *     
     */
    public void setVnfFlavours(VnfFlavours value) {
        this.vnfFlavours = value;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link Dependencies }
     *     
     */
    public Dependencies getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dependencies }
     *     
     */
    public void setDependencies(Dependencies value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the autoscalingPolicies property.
     * 
     * @return
     *     possible object is
     *     {@link AutoscalingPolicies }
     *     
     */
    public AutoscalingPolicies getAutoscalingPolicies() {
        return autoscalingPolicies;
    }

    /**
     * Sets the value of the autoscalingPolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutoscalingPolicies }
     *     
     */
    public void setAutoscalingPolicies(AutoscalingPolicies value) {
        this.autoscalingPolicies = value;
    }

}
