//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.23 at 09:37:17 上午 CST 
//


package com.culabs.nfvo.model.vnfd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}init"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}terminate"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.vnfd}graceful-shutdown"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "init",
    "terminate",
    "gracefulShutdown"
})
@XmlRootElement(name = "workflows")
public class Workflows {

    protected Init init;
    protected Terminate terminate;
    @XmlElement(name = "graceful-shutdown")
    protected GracefulShutdown gracefulShutdown;

    /**
     * Gets the value of the init property.
     * 
     * @return
     *     possible object is
     *     {@link Init }
     *     
     */
    public Init getInit() {
        return init;
    }

    /**
     * Sets the value of the init property.
     * 
     * @param value
     *     allowed object is
     *     {@link Init }
     *     
     */
    public void setInit(Init value) {
        this.init = value;
    }

    /**
     * Gets the value of the terminate property.
     * 
     * @return
     *     possible object is
     *     {@link Terminate }
     *     
     */
    public Terminate getTerminate() {
        return terminate;
    }

    /**
     * Sets the value of the terminate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terminate }
     *     
     */
    public void setTerminate(Terminate value) {
        this.terminate = value;
    }

    /**
     * Gets the value of the gracefulShutdown property.
     * 
     * @return
     *     possible object is
     *     {@link GracefulShutdown }
     *     
     */
    public GracefulShutdown getGracefulShutdown() {
        return gracefulShutdown;
    }

    /**
     * Sets the value of the gracefulShutdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link GracefulShutdown }
     *     
     */
    public void setGracefulShutdown(GracefulShutdown value) {
        this.gracefulShutdown = value;
    }

}
