package com.culabs.nfvo.dao;

import java.util.List;

import com.culabs.nfvo.model.db.DBAcl;

public interface DBAclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int deleteByPrimaryKey(String acl_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int insert(DBAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int insertSelective(DBAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    DBAcl selectByPrimaryKey(String acl_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int updateByPrimaryKeySelective(DBAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int updateByPrimaryKey(DBAcl record);

    List<DBAcl> selectList();
}