package com.culabs.nfvo.dao;

import java.util.List;

import com.culabs.nfvo.model.db.DBNsd;

public interface DBNsdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templ_nsd
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    int deleteByPrimaryKey(String template_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templ_nsd
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    int insert(DBNsd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templ_nsd
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    int insertSelective(DBNsd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templ_nsd
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    DBNsd selectByPrimaryKey(String template_id);

    /**
     * 
     * @Title: selectList 
     * @Description: TODO
     * @param @param template_id
     * @param @return 
     * @return DBNsd 
     * @throws
     */
    List<DBNsd> selectList(String type);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templ_nsd
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    int updateByPrimaryKeySelective(DBNsd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templ_nsd
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(DBNsd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table templ_nsd
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    int updateByPrimaryKey(DBNsd record);
}