package com.culabs.nfvo.dao;

import com.culabs.nfvo.model.db.DBPort;

public interface DBPortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int deleteByPrimaryKey(String port_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int insert(DBPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int insertSelective(DBPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    DBPort selectByPrimaryKey(String port_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int updateByPrimaryKeySelective(DBPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int updateByPrimaryKey(DBPort record);
}