package com.culabs.nfvo.dao;

import java.util.List;

import com.culabs.nfvo.model.db.DBSubnet;

public interface DBSubnetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnet
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int deleteByPrimaryKey(String subnet_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnet
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int insert(DBSubnet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnet
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int insertSelective(DBSubnet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnet
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    DBSubnet selectByPrimaryKey(String subnet_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnet
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int updateByPrimaryKeySelective(DBSubnet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnet
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    int updateByPrimaryKey(DBSubnet record);

    List<DBSubnet> selectList();
}