package com.culabs.nfvo.model.db;

public class DBAclSubnet {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column acl_subnet.acl_subnet_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    private String acl_subnet_id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column acl_subnet.acl_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    private String acl_id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column acl_subnet.tenant_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    private String tenant_id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column acl_subnet.subnet_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    private String subnet_id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column acl_subnet.name
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column acl_subnet.status
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column acl_subnet.acl_subnet_id
     * @return  the value of acl_subnet.acl_subnet_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public String getAcl_subnet_id() {
        return acl_subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column acl_subnet.acl_subnet_id
     * @param acl_subnet_id  the value for acl_subnet.acl_subnet_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public void setAcl_subnet_id(String acl_subnet_id) {
        this.acl_subnet_id = acl_subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column acl_subnet.acl_id
     * @return  the value of acl_subnet.acl_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public String getAcl_id() {
        return acl_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column acl_subnet.acl_id
     * @param acl_id  the value for acl_subnet.acl_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public void setAcl_id(String acl_id) {
        this.acl_id = acl_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column acl_subnet.tenant_id
     * @return  the value of acl_subnet.tenant_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public String getTenant_id() {
        return tenant_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column acl_subnet.tenant_id
     * @param tenant_id  the value for acl_subnet.tenant_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public void setTenant_id(String tenant_id) {
        this.tenant_id = tenant_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column acl_subnet.subnet_id
     * @return  the value of acl_subnet.subnet_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public String getSubnet_id() {
        return subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column acl_subnet.subnet_id
     * @param subnet_id  the value for acl_subnet.subnet_id
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public void setSubnet_id(String subnet_id) {
        this.subnet_id = subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column acl_subnet.name
     * @return  the value of acl_subnet.name
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column acl_subnet.name
     * @param name  the value for acl_subnet.name
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column acl_subnet.status
     * @return  the value of acl_subnet.status
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column acl_subnet.status
     * @param status  the value for acl_subnet.status
     * @mbggenerated  Thu Apr 30 15:32:13 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }
}