package com.culabs.nfvo.model.db;

public class DBInstanceServer
{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column instance_server.id
	 * 
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column instance_server.instance_id
	 * 
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	private String instance_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column instance_server.server_id
	 * 
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	private String server_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column instance_server.vnf_name
	 * 
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	private String vnf_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column instance_server.vnf_name
	 * 
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	private String vnf_name;
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column instance_server.instancenum
	 * 
	 * @return the value of instance_server.instancenum
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	private Integer instancenum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column instance_server.sequence
	 * 
	 * @return the value of instance_server.sequence
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	private Integer sequence;

	public Integer getId()
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column instance_server.id
	 * 
	 * @param id
	 *            the value for instance_server.id
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public void setId(Integer id)
	{
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column instance_server.instance_id
	 * 
	 * @return the value of instance_server.instance_id
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public String getInstance_id()
	{
		return instance_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column instance_server.instance_id
	 * 
	 * @param instance_id
	 *            the value for instance_server.instance_id
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public void setInstance_id(String instance_id)
	{
		this.instance_id = instance_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column instance_server.server_id
	 * 
	 * @return the value of instance_server.server_id
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public String getServer_id()
	{
		return server_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column instance_server.server_id
	 * 
	 * @param server_id
	 *            the value for instance_server.server_id
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public void setServer_id(String server_id)
	{
		this.server_id = server_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column instance_server.vnf_id
	 * 
	 * @return the value of instance_server.vnf_id
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public String getVnf_id()
	{
		return vnf_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column instance_server.vnf_id
	 * 
	 * @param vnf_id
	 *            the value for instance_server.vnf_id
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public void setVnf_id(String vnf_id)
	{
		this.vnf_id = vnf_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column instance_server.vnf_name
	 * 
	 * @return the value of instance_server.vnf_name
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public String getVnf_name()
	{
		return vnf_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column instance_server.vnf_name
	 * 
	 * @param vnf_name
	 *            the value for instance_server.vnf_name
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public void setVnf_name(String vnf_name)
	{
		this.vnf_name = vnf_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column instance_server.instancenum
	 * 
	 * @return the value of instance_server.instancenum
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public Integer getInstancenum()
	{
		return instancenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column instance_server.instancenum
	 * 
	 * @param instancenum
	 *            the value for instance_server.instancenum
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public void setInstancenum(Integer instancenum)
	{
		this.instancenum = instancenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column instance_server.sequence
	 * 
	 * @return the value of instance_server.sequence
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public Integer getSequence()
	{
		return sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column instance_server.sequence
	 * 
	 * @param sequence
	 *            the value for instance_server.sequence
	 * @mbggenerated Tue May 05 16:36:51 CST 2015
	 */
	public void setSequence(Integer sequence)
	{
		this.sequence = sequence;
	}

}