package com.culabs.nfvo.model.db;

public class DBNat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nat.nat_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String nat_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nat.public_ip_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String public_ip_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nat.public_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String public_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nat.tenant_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String tenant_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nat.type
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nat.igw_router_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String igw_router_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nat.protocol
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nat.fixed_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String fixed_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nat.source_port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String source_port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nat.destination_port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String destination_port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nat.status
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nat.nat_id
     *
     * @return the value of nat.nat_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getNat_id() {
        return nat_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nat.nat_id
     *
     * @param nat_id the value for nat.nat_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setNat_id(String nat_id) {
        this.nat_id = nat_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nat.public_ip_id
     *
     * @return the value of nat.public_ip_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getPublic_ip_id() {
        return public_ip_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nat.public_ip_id
     *
     * @param public_ip_id the value for nat.public_ip_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setPublic_ip_id(String public_ip_id) {
        this.public_ip_id = public_ip_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nat.public_ip
     *
     * @return the value of nat.public_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getPublic_ip() {
        return public_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nat.public_ip
     *
     * @param public_ip the value for nat.public_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setPublic_ip(String public_ip) {
        this.public_ip = public_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nat.tenant_id
     *
     * @return the value of nat.tenant_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getTenant_id() {
        return tenant_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nat.tenant_id
     *
     * @param tenant_id the value for nat.tenant_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setTenant_id(String tenant_id) {
        this.tenant_id = tenant_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nat.type
     *
     * @return the value of nat.type
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nat.type
     *
     * @param type the value for nat.type
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nat.igw_router_id
     *
     * @return the value of nat.igw_router_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getIgw_router_id() {
        return igw_router_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nat.igw_router_id
     *
     * @param igw_router_id the value for nat.igw_router_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setIgw_router_id(String igw_router_id) {
        this.igw_router_id = igw_router_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nat.protocol
     *
     * @return the value of nat.protocol
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nat.protocol
     *
     * @param protocol the value for nat.protocol
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nat.fixed_ip
     *
     * @return the value of nat.fixed_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getFixed_ip() {
        return fixed_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nat.fixed_ip
     *
     * @param fixed_ip the value for nat.fixed_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setFixed_ip(String fixed_ip) {
        this.fixed_ip = fixed_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nat.source_port
     *
     * @return the value of nat.source_port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getSource_port() {
        return source_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nat.source_port
     *
     * @param source_port the value for nat.source_port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setSource_port(String source_port) {
        this.source_port = source_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nat.destination_port
     *
     * @return the value of nat.destination_port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getDestination_port() {
        return destination_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nat.destination_port
     *
     * @param destination_port the value for nat.destination_port
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setDestination_port(String destination_port) {
        this.destination_port = destination_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nat.status
     *
     * @return the value of nat.status
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nat.status
     *
     * @param status the value for nat.status
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }
}