package com.culabs.nfvo.model.db;

public class DBNsdVnfdKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templ_nsd_nfvd.template_id
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    private String template_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templ_nsd_nfvd.vnfd_id
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    private String vnfd_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templ_nsd_nfvd.template_id
     *
     * @return the value of templ_nsd_nfvd.template_id
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public String getTemplate_id() {
        return template_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templ_nsd_nfvd.template_id
     *
     * @param template_id the value for templ_nsd_nfvd.template_id
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public void setTemplate_id(String template_id) {
        this.template_id = template_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templ_nsd_nfvd.vnfd_id
     *
     * @return the value of templ_nsd_nfvd.vnfd_id
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public String getVnfd_id() {
        return vnfd_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templ_nsd_nfvd.vnfd_id
     *
     * @param vnfd_id the value for templ_nsd_nfvd.vnfd_id
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public void setVnfd_id(String vnfd_id) {
        this.vnfd_id = vnfd_id;
    }

	@Override
	public String toString()
	{
		return "DBNsdVnfdKey [template_id=" + template_id + ", vnfd_id="
				+ vnfd_id + "]";
	}
    
}