package com.culabs.nfvo.model.db;

public class DBPool {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pool.id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pool.name
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pool.subnet_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String subnet_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pool.tenant_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String tenant_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pool.protocol
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pool.lb_method
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String lb_method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pool.status
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pool.description
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pool.id
     *
     * @return the value of pool.id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pool.id
     *
     * @param id the value for pool.id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pool.name
     *
     * @return the value of pool.name
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pool.name
     *
     * @param name the value for pool.name
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pool.subnet_id
     *
     * @return the value of pool.subnet_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getSubnet_id() {
        return subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pool.subnet_id
     *
     * @param subnet_id the value for pool.subnet_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setSubnet_id(String subnet_id) {
        this.subnet_id = subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pool.tenant_id
     *
     * @return the value of pool.tenant_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getTenant_id() {
        return tenant_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pool.tenant_id
     *
     * @param tenant_id the value for pool.tenant_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setTenant_id(String tenant_id) {
        this.tenant_id = tenant_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pool.protocol
     *
     * @return the value of pool.protocol
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pool.protocol
     *
     * @param protocol the value for pool.protocol
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pool.lb_method
     *
     * @return the value of pool.lb_method
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getLb_method() {
        return lb_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pool.lb_method
     *
     * @param lb_method the value for pool.lb_method
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setLb_method(String lb_method) {
        this.lb_method = lb_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pool.status
     *
     * @return the value of pool.status
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pool.status
     *
     * @param status the value for pool.status
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pool.description
     *
     * @return the value of pool.description
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pool.description
     *
     * @param description the value for pool.description
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}