package com.culabs.nfvo.model.db;

public class DBRoutingRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routing_rule.routing_rule_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String routing_rule_id;
    
    private String tenant_id ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routing_rule.routing_table_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String routing_table_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routing_rule.name
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routing_rule.prefix
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String prefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routing_rule.nexthop
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String nexthop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routing_rule.gw_router_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String gw_router_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routing_rule.status
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routing_rule.type
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routing_rule.routing_rule_id
     *
     * @return the value of routing_rule.routing_rule_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getRouting_rule_id() {
        return routing_rule_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routing_rule.routing_rule_id
     *
     * @param routing_rule_id the value for routing_rule.routing_rule_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setRouting_rule_id(String routing_rule_id) {
        this.routing_rule_id = routing_rule_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routing_rule.routing_table_id
     *
     * @return the value of routing_rule.routing_table_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getRouting_table_id() {
        return routing_table_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routing_rule.routing_table_id
     *
     * @param routing_table_id the value for routing_rule.routing_table_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setRouting_table_id(String routing_table_id) {
        this.routing_table_id = routing_table_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routing_rule.name
     *
     * @return the value of routing_rule.name
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routing_rule.name
     *
     * @param name the value for routing_rule.name
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routing_rule.prefix
     *
     * @return the value of routing_rule.prefix
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routing_rule.prefix
     *
     * @param prefix the value for routing_rule.prefix
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routing_rule.nexthop
     *
     * @return the value of routing_rule.nexthop
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getNexthop() {
        return nexthop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routing_rule.nexthop
     *
     * @param nexthop the value for routing_rule.nexthop
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setNexthop(String nexthop) {
        this.nexthop = nexthop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routing_rule.gw_router_id
     *
     * @return the value of routing_rule.gw_router_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getGw_router_id() {
        return gw_router_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routing_rule.gw_router_id
     *
     * @param gw_router_id the value for routing_rule.gw_router_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setGw_router_id(String gw_router_id) {
        this.gw_router_id = gw_router_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routing_rule.status
     *
     * @return the value of routing_rule.status
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routing_rule.status
     *
     * @param status the value for routing_rule.status
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routing_rule.type
     *
     * @return the value of routing_rule.type
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routing_rule.type
     *
     * @param type the value for routing_rule.type
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

	public String getTenant_id() {
		return tenant_id;
	}

	public void setTenant_id(String tenant_id) {
		this.tenant_id = tenant_id;
	}

}