package com.culabs.nfvo.model.db;

public class DBSubnet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.subnet_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String subnet_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.name
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.network_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String network_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.tenant_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String tenant_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.gateway_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String gateway_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.ip_version
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String ip_version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.cidr
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String cidr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.enable_dhcp
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private Boolean enable_dhcp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.allocation_pools_start
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String allocation_pools_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.allocation_pools_end
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String allocation_pools_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.dns_nameservers
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String dns_nameservers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.host_routes_destination
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String host_routes_destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.host_routes_nexthop
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String host_routes_nexthop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.ipv6_ra_mode
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String ipv6_ra_mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subnet.ipv6_address_mode
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String ipv6_address_mode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.subnet_id
     *
     * @return the value of subnet.subnet_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getSubnet_id() {
        return subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.subnet_id
     *
     * @param subnet_id the value for subnet.subnet_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setSubnet_id(String subnet_id) {
        this.subnet_id = subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.name
     *
     * @return the value of subnet.name
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.name
     *
     * @param name the value for subnet.name
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.network_id
     *
     * @return the value of subnet.network_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getNetwork_id() {
        return network_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.network_id
     *
     * @param network_id the value for subnet.network_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setNetwork_id(String network_id) {
        this.network_id = network_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.tenant_id
     *
     * @return the value of subnet.tenant_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getTenant_id() {
        return tenant_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.tenant_id
     *
     * @param tenant_id the value for subnet.tenant_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setTenant_id(String tenant_id) {
        this.tenant_id = tenant_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.gateway_ip
     *
     * @return the value of subnet.gateway_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getGateway_ip() {
        return gateway_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.gateway_ip
     *
     * @param gateway_ip the value for subnet.gateway_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setGateway_ip(String gateway_ip) {
        this.gateway_ip = gateway_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.ip_version
     *
     * @return the value of subnet.ip_version
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getIp_version() {
        return ip_version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.ip_version
     *
     * @param ip_version the value for subnet.ip_version
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setIp_version(String ip_version) {
        this.ip_version = ip_version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.cidr
     *
     * @return the value of subnet.cidr
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getCidr() {
        return cidr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.cidr
     *
     * @param cidr the value for subnet.cidr
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setCidr(String cidr) {
        this.cidr = cidr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.enable_dhcp
     *
     * @return the value of subnet.enable_dhcp
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public Boolean getEnable_dhcp() {
        return enable_dhcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.enable_dhcp
     *
     * @param enable_dhcp the value for subnet.enable_dhcp
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setEnable_dhcp(Boolean enable_dhcp) {
        this.enable_dhcp = enable_dhcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.allocation_pools_start
     *
     * @return the value of subnet.allocation_pools_start
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getAllocation_pools_start() {
        return allocation_pools_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.allocation_pools_start
     *
     * @param allocation_pools_start the value for subnet.allocation_pools_start
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setAllocation_pools_start(String allocation_pools_start) {
        this.allocation_pools_start = allocation_pools_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.allocation_pools_end
     *
     * @return the value of subnet.allocation_pools_end
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getAllocation_pools_end() {
        return allocation_pools_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.allocation_pools_end
     *
     * @param allocation_pools_end the value for subnet.allocation_pools_end
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setAllocation_pools_end(String allocation_pools_end) {
        this.allocation_pools_end = allocation_pools_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.dns_nameservers
     *
     * @return the value of subnet.dns_nameservers
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getDns_nameservers() {
        return dns_nameservers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.dns_nameservers
     *
     * @param dns_nameservers the value for subnet.dns_nameservers
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setDns_nameservers(String dns_nameservers) {
        this.dns_nameservers = dns_nameservers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.host_routes_destination
     *
     * @return the value of subnet.host_routes_destination
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getHost_routes_destination() {
        return host_routes_destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.host_routes_destination
     *
     * @param host_routes_destination the value for subnet.host_routes_destination
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setHost_routes_destination(String host_routes_destination) {
        this.host_routes_destination = host_routes_destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.host_routes_nexthop
     *
     * @return the value of subnet.host_routes_nexthop
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getHost_routes_nexthop() {
        return host_routes_nexthop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.host_routes_nexthop
     *
     * @param host_routes_nexthop the value for subnet.host_routes_nexthop
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setHost_routes_nexthop(String host_routes_nexthop) {
        this.host_routes_nexthop = host_routes_nexthop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.ipv6_ra_mode
     *
     * @return the value of subnet.ipv6_ra_mode
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getIpv6_ra_mode() {
        return ipv6_ra_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.ipv6_ra_mode
     *
     * @param ipv6_ra_mode the value for subnet.ipv6_ra_mode
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setIpv6_ra_mode(String ipv6_ra_mode) {
        this.ipv6_ra_mode = ipv6_ra_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subnet.ipv6_address_mode
     *
     * @return the value of subnet.ipv6_address_mode
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getIpv6_address_mode() {
        return ipv6_address_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subnet.ipv6_address_mode
     *
     * @param ipv6_address_mode the value for subnet.ipv6_address_mode
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setIpv6_address_mode(String ipv6_address_mode) {
        this.ipv6_address_mode = ipv6_address_mode;
    }
}