package com.culabs.nfvo.model.db;

public class DBVip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.name
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.subnet_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String subnet_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.tenant_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String tenant_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.pool_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String pool_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.adress
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String adress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.protocal
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String protocal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.protocal_port
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String protocal_port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.status
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.id
     *
     * @return the value of vip.id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.id
     *
     * @param id the value for vip.id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.name
     *
     * @return the value of vip.name
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.name
     *
     * @param name the value for vip.name
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.subnet_id
     *
     * @return the value of vip.subnet_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getSubnet_id() {
        return subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.subnet_id
     *
     * @param subnet_id the value for vip.subnet_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setSubnet_id(String subnet_id) {
        this.subnet_id = subnet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.tenant_id
     *
     * @return the value of vip.tenant_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getTenant_id() {
        return tenant_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.tenant_id
     *
     * @param tenant_id the value for vip.tenant_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setTenant_id(String tenant_id) {
        this.tenant_id = tenant_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.pool_id
     *
     * @return the value of vip.pool_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getPool_id() {
        return pool_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.pool_id
     *
     * @param pool_id the value for vip.pool_id
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setPool_id(String pool_id) {
        this.pool_id = pool_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.adress
     *
     * @return the value of vip.adress
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.adress
     *
     * @param adress the value for vip.adress
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setAdress(String adress) {
        this.adress = adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.protocal
     *
     * @return the value of vip.protocal
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getProtocal() {
        return protocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.protocal
     *
     * @param protocal the value for vip.protocal
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setProtocal(String protocal) {
        this.protocal = protocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.protocal_port
     *
     * @return the value of vip.protocal_port
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getProtocal_port() {
        return protocal_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.protocal_port
     *
     * @param protocal_port the value for vip.protocal_port
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setProtocal_port(String protocal_port) {
        this.protocal_port = protocal_port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.status
     *
     * @return the value of vip.status
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.status
     *
     * @param status the value for vip.status
     *
     * @mbggenerated Mon May 25 14:47:06 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }
}