package com.culabs.nfvo.model.db;

public class DBVnfd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templ_vnfd.vnfd_id
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    private String vnfd_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templ_vnfd.name
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templ_vnfd.provider
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    private String provider;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templ_vnfd.description
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templ_vnfd.version
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column templ_vnfd.content
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templ_vnfd.vnfd_id
     *
     * @return the value of templ_vnfd.vnfd_id
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public String getVnfd_id() {
        return vnfd_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templ_vnfd.vnfd_id
     *
     * @param vnfd_id the value for templ_vnfd.vnfd_id
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public void setVnfd_id(String vnfd_id) {
        this.vnfd_id = vnfd_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templ_vnfd.name
     *
     * @return the value of templ_vnfd.name
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templ_vnfd.name
     *
     * @param name the value for templ_vnfd.name
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templ_vnfd.provider
     *
     * @return the value of templ_vnfd.provider
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templ_vnfd.provider
     *
     * @param provider the value for templ_vnfd.provider
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templ_vnfd.description
     *
     * @return the value of templ_vnfd.description
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templ_vnfd.description
     *
     * @param description the value for templ_vnfd.description
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templ_vnfd.version
     *
     * @return the value of templ_vnfd.version
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templ_vnfd.version
     *
     * @param version the value for templ_vnfd.version
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column templ_vnfd.content
     *
     * @return the value of templ_vnfd.content
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column templ_vnfd.content
     *
     * @param content the value for templ_vnfd.content
     *
     * @mbggenerated Sat Apr 25 15:02:04 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

	@Override
	public String toString()
	{
		return "DBVnfd [vnfd_id=" + vnfd_id + ", name=" + name + ", provider="
				+ provider + ", description=" + description + ", version="
				+ version + ", content=" + content + "]";
	}
    
}