package com.culabs.nfvo.model.db;

public class DBVpnConnectionPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.vpn_connection_point_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String vpn_connection_point_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.name
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.vgw_router_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String vgw_router_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.public_ip_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String public_ip_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.vpn_type
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String vpn_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.tunnel_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String tunnel_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.local_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String local_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.remote_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String remote_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.extra_params_static_routes
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String extra_params_static_routes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.extra_params_interface
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String extra_params_interface;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.extra_params_remote_prefix
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String extra_params_remote_prefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.extra_params_local_prefix
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String extra_params_local_prefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpn_connection_point.status
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.vpn_connection_point_id
     *
     * @return the value of vpn_connection_point.vpn_connection_point_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getVpn_connection_point_id() {
        return vpn_connection_point_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.vpn_connection_point_id
     *
     * @param vpn_connection_point_id the value for vpn_connection_point.vpn_connection_point_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setVpn_connection_point_id(String vpn_connection_point_id) {
        this.vpn_connection_point_id = vpn_connection_point_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.name
     *
     * @return the value of vpn_connection_point.name
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.name
     *
     * @param name the value for vpn_connection_point.name
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.vgw_router_id
     *
     * @return the value of vpn_connection_point.vgw_router_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getVgw_router_id() {
        return vgw_router_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.vgw_router_id
     *
     * @param vgw_router_id the value for vpn_connection_point.vgw_router_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setVgw_router_id(String vgw_router_id) {
        this.vgw_router_id = vgw_router_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.public_ip_id
     *
     * @return the value of vpn_connection_point.public_ip_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getPublic_ip_id() {
        return public_ip_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.public_ip_id
     *
     * @param public_ip_id the value for vpn_connection_point.public_ip_id
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setPublic_ip_id(String public_ip_id) {
        this.public_ip_id = public_ip_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.vpn_type
     *
     * @return the value of vpn_connection_point.vpn_type
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getVpn_type() {
        return vpn_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.vpn_type
     *
     * @param vpn_type the value for vpn_connection_point.vpn_type
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setVpn_type(String vpn_type) {
        this.vpn_type = vpn_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.tunnel_ip
     *
     * @return the value of vpn_connection_point.tunnel_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getTunnel_ip() {
        return tunnel_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.tunnel_ip
     *
     * @param tunnel_ip the value for vpn_connection_point.tunnel_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setTunnel_ip(String tunnel_ip) {
        this.tunnel_ip = tunnel_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.local_ip
     *
     * @return the value of vpn_connection_point.local_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getLocal_ip() {
        return local_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.local_ip
     *
     * @param local_ip the value for vpn_connection_point.local_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setLocal_ip(String local_ip) {
        this.local_ip = local_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.remote_ip
     *
     * @return the value of vpn_connection_point.remote_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getRemote_ip() {
        return remote_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.remote_ip
     *
     * @param remote_ip the value for vpn_connection_point.remote_ip
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setRemote_ip(String remote_ip) {
        this.remote_ip = remote_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.extra_params_static_routes
     *
     * @return the value of vpn_connection_point.extra_params_static_routes
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getExtra_params_static_routes() {
        return extra_params_static_routes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.extra_params_static_routes
     *
     * @param extra_params_static_routes the value for vpn_connection_point.extra_params_static_routes
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setExtra_params_static_routes(String extra_params_static_routes) {
        this.extra_params_static_routes = extra_params_static_routes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.extra_params_interface
     *
     * @return the value of vpn_connection_point.extra_params_interface
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getExtra_params_interface() {
        return extra_params_interface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.extra_params_interface
     *
     * @param extra_params_interface the value for vpn_connection_point.extra_params_interface
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setExtra_params_interface(String extra_params_interface) {
        this.extra_params_interface = extra_params_interface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.extra_params_remote_prefix
     *
     * @return the value of vpn_connection_point.extra_params_remote_prefix
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getExtra_params_remote_prefix() {
        return extra_params_remote_prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.extra_params_remote_prefix
     *
     * @param extra_params_remote_prefix the value for vpn_connection_point.extra_params_remote_prefix
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setExtra_params_remote_prefix(String extra_params_remote_prefix) {
        this.extra_params_remote_prefix = extra_params_remote_prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.extra_params_local_prefix
     *
     * @return the value of vpn_connection_point.extra_params_local_prefix
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getExtra_params_local_prefix() {
        return extra_params_local_prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.extra_params_local_prefix
     *
     * @param extra_params_local_prefix the value for vpn_connection_point.extra_params_local_prefix
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setExtra_params_local_prefix(String extra_params_local_prefix) {
        this.extra_params_local_prefix = extra_params_local_prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpn_connection_point.status
     *
     * @return the value of vpn_connection_point.status
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpn_connection_point.status
     *
     * @param status the value for vpn_connection_point.status
     *
     * @mbggenerated Tue Apr 28 19:19:52 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }
}