//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.23 at 09:36:36 上午 CST 
//


package com.culabs.nfvo.model.nsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}vnf"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}vnf-connection-point"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vnf",
    "vnfConnectionPoint"
})
@XmlRootElement(name = "dst-connection-point")
public class DstConnectionPoint {

    @XmlElement(required = true)
    protected String vnf;
    @XmlElement(name = "vnf-connection-point", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String vnfConnectionPoint;

    /**
     * Gets the value of the vnf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnf() {
        return vnf;
    }

    /**
     * Sets the value of the vnf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnf(String value) {
        this.vnf = value;
    }

    /**
     * Gets the value of the vnfConnectionPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnfConnectionPoint() {
        return vnfConnectionPoint;
    }

    /**
     * Sets the value of the vnfConnectionPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnfConnectionPoint(String value) {
        this.vnfConnectionPoint = value;
    }

}
