//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.23 at 09:36:36 上午 CST 
//


package com.culabs.nfvo.model.nsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}end-point-src"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{urn:com.culabs.nfvo.model.nsd}vld"/>
 *           &lt;element ref="{urn:com.culabs.nfvo.model.nsd}dst-connection-point"/>
 *           &lt;element ref="{urn:com.culabs.nfvo.model.nsd}forwarding-policy"/>
 *           &lt;element ref="{urn:com.culabs.nfvo.model.nsd}src-connection-point"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "endPointSrc",
    "vldOrDstConnectionPointOrForwardingPolicy"
})
@XmlRootElement(name = "network-forwarding-path")
public class NetworkForwardingPath {

    @XmlElement(name = "end-point-src", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String endPointSrc;
    @XmlElements({
        @XmlElement(name = "vld", type = Vld.class),
        @XmlElement(name = "forwarding-policy", type = ForwardingPolicy.class),
        @XmlElement(name = "dst-connection-point", type = DstConnectionPoint.class),
        @XmlElement(name = "src-connection-point", type = SrcConnectionPoint.class)
    })
    protected List<Object> vldOrDstConnectionPointOrForwardingPolicy;

    /**
     * Gets the value of the endPointSrc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndPointSrc() {
        return endPointSrc;
    }

    /**
     * Sets the value of the endPointSrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndPointSrc(String value) {
        this.endPointSrc = value;
    }

    /**
     * Gets the value of the vldOrDstConnectionPointOrForwardingPolicy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vldOrDstConnectionPointOrForwardingPolicy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVldOrDstConnectionPointOrForwardingPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Vld }
     * {@link ForwardingPolicy }
     * {@link DstConnectionPoint }
     * {@link SrcConnectionPoint }
     * 
     * 
     */
    public List<Object> getVldOrDstConnectionPointOrForwardingPolicy() {
        if (vldOrDstConnectionPointOrForwardingPolicy == null) {
            vldOrDstConnectionPointOrForwardingPolicy = new ArrayList<Object>();
        }
        return this.vldOrDstConnectionPointOrForwardingPolicy;
    }

}
