//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.23 at 09:36:36 上午 CST 
//


package com.culabs.nfvo.model.nsd;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}name"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}nsd-id"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}provider"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}type"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}description"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}version"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}monitoring-params"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}end-points"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}vlds"/>
 *         &lt;element ref="{urn:com.culabs.nfvo.model.nsd}ns-flavours"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "nsdId",
    "provider",
    "type",
    "description",
    "version",
    "monitoringParams",
    "endPoints",
    "vlds",
    "nsFlavours"
})
@XmlRootElement(name = "nsd")
public class Nsd {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "nsd-id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nsdId;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String provider;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected BigDecimal version;
    @XmlElement(name = "monitoring-params", required = true)
    protected MonitoringParams monitoringParams;
    @XmlElement(name = "end-points", required = true)
    protected EndPoints endPoints;
    @XmlElement(required = true)
    protected Vlds vlds;
    @XmlElement(name = "ns-flavours", required = true)
    protected NsFlavours nsFlavours;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nsdId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsdId() {
        return nsdId;
    }

    /**
     * Sets the value of the nsdId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsdId(String value) {
        this.nsdId = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the monitoringParams property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringParams }
     *     
     */
    public MonitoringParams getMonitoringParams() {
        return monitoringParams;
    }

    /**
     * Sets the value of the monitoringParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringParams }
     *     
     */
    public void setMonitoringParams(MonitoringParams value) {
        this.monitoringParams = value;
    }

    /**
     * Gets the value of the endPoints property.
     * 
     * @return
     *     possible object is
     *     {@link EndPoints }
     *     
     */
    public EndPoints getEndPoints() {
        return endPoints;
    }

    /**
     * Sets the value of the endPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndPoints }
     *     
     */
    public void setEndPoints(EndPoints value) {
        this.endPoints = value;
    }

    /**
     * Gets the value of the vlds property.
     * 
     * @return
     *     possible object is
     *     {@link Vlds }
     *     
     */
    public Vlds getVlds() {
        return vlds;
    }

    /**
     * Sets the value of the vlds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vlds }
     *     
     */
    public void setVlds(Vlds value) {
        this.vlds = value;
    }

    /**
     * Gets the value of the nsFlavours property.
     * 
     * @return
     *     possible object is
     *     {@link NsFlavours }
     *     
     */
    public NsFlavours getNsFlavours() {
        return nsFlavours;
    }

    /**
     * Sets the value of the nsFlavours property.
     * 
     * @param value
     *     allowed object is
     *     {@link NsFlavours }
     *     
     */
    public void setNsFlavours(NsFlavours value) {
        this.nsFlavours = value;
    }

}
