//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.23 at 09:36:36 上午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:com.culabs.nfvo.model.nsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.culabs.nfvo.model.nsd;
