package com.culabs.unicomportal.dao;

import com.culabs.unicomportal.model.db.DBAlerts;

public interface DBAlertsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerts
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerts
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insert(DBAlerts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerts
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insertSelective(DBAlerts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerts
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    DBAlerts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerts
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeySelective(DBAlerts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alerts
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKey(DBAlerts record);
}