package com.culabs.unicomportal.dao;

import com.culabs.unicomportal.model.db.DBAlarmMeters;

public interface DBAlarmMetersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_meters
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_meters
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insert(DBAlarmMeters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_meters
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insertSelective(DBAlarmMeters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_meters
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    DBAlarmMeters selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_meters
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeySelective(DBAlarmMeters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_meters
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(DBAlarmMeters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_meters
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKey(DBAlarmMeters record);
}