package com.culabs.unicomportal.dao;

import com.culabs.unicomportal.model.db.DBAlarmBindings;

public interface DBAlarmBindingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_bindings
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_bindings
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insert(DBAlarmBindings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_bindings
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insertSelective(DBAlarmBindings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_bindings
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    DBAlarmBindings selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_bindings
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeySelective(DBAlarmBindings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_bindings
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKey(DBAlarmBindings record);
}