package com.culabs.unicomportal.dao;

import com.culabs.unicomportal.model.db.DBAtomdetails;
import com.culabs.unicomportal.model.db.DBAtomdetailsWithBLOBs;

public interface DBAtomdetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomdetails
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomdetails
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insert(DBAtomdetailsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomdetails
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insertSelective(DBAtomdetailsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomdetails
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    DBAtomdetailsWithBLOBs selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomdetails
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeySelective(DBAtomdetailsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomdetails
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(DBAtomdetailsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atomdetails
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKey(DBAtomdetails record);
}