package com.culabs.unicomportal.dao;

import com.culabs.unicomportal.model.db.DBLbVips;

public interface DBLbVipsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_vips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_vips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insert(DBLbVips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_vips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insertSelective(DBLbVips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_vips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    DBLbVips selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_vips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeySelective(DBLbVips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_vips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(DBLbVips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_vips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKey(DBLbVips record);
}