package com.culabs.unicomportal.dao;

import com.culabs.unicomportal.model.db.DBLbPoolStatistics;

public interface DBLbPoolStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_pool_statistics
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_pool_statistics
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insert(DBLbPoolStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_pool_statistics
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insertSelective(DBLbPoolStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_pool_statistics
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    DBLbPoolStatistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_pool_statistics
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeySelective(DBLbPoolStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lb_pool_statistics
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKey(DBLbPoolStatistics record);
}