package com.culabs.unicomportal.dao;

import com.culabs.unicomportal.model.db.DBSubnets;
import com.culabs.unicomportal.model.db.DBSubnetsWithBLOBs;

public interface DBSubnetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnets
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnets
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insert(DBSubnetsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnets
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insertSelective(DBSubnetsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnets
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    DBSubnetsWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnets
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeySelective(DBSubnetsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnets
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(DBSubnetsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subnets
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKey(DBSubnets record);

    DBSubnets selectByUUID(String uuid);

	DBSubnets selectByName(String name);
}