package com.culabs.unicomportal.dao;

import com.culabs.unicomportal.model.db.DBSystemProperties;

public interface DBSystemPropertiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insert(DBSystemProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insertSelective(DBSystemProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    DBSystemProperties selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeySelective(DBSystemProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKey(DBSystemProperties record);
}