package com.culabs.unicomportal.dao;

import com.culabs.unicomportal.model.db.DBUserProperties;

public interface DBUserPropertiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insert(DBUserProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insertSelective(DBUserProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    DBUserProperties selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeySelective(DBUserProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_properties
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKey(DBUserProperties record);
}