package com.culabs.unicomportal.dao;

import com.culabs.unicomportal.model.db.DBVirtualrouterFloatingips;

public interface DBVirtualrouterFloatingipsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtualrouter_floatingips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtualrouter_floatingips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insert(DBVirtualrouterFloatingips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtualrouter_floatingips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int insertSelective(DBVirtualrouterFloatingips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtualrouter_floatingips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    DBVirtualrouterFloatingips selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtualrouter_floatingips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKeySelective(DBVirtualrouterFloatingips record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virtualrouter_floatingips
     *
     * @mbggenerated Tue May 26 15:53:09 CST 2015
     */
    int updateByPrimaryKey(DBVirtualrouterFloatingips record);
}